//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Entity
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using LighTake.Infrastructure.Seedwork;
    
    public partial class AbnormalWayBillLog : Entity
    {
    
        ICollection<WayBillInfo> _wayBillInfos;
    
    
        public virtual int AbnormalID { get; set; }
        public virtual int OperateType { get; set; }
        public virtual int AbnormalStatus { get; set; }
        public virtual string AbnormalDescription { get; set; }
        public virtual string CreatedBy { get; set; }
        public virtual System.DateTime CreatedOn { get; set; }
        public virtual string LastUpdatedBy { get; set; }
        public virtual System.DateTime LastUpdatedOn { get; set; }
    
        public virtual ICollection<WayBillInfo> WayBillInfos 
    	{
            get { return _wayBillInfos  ?? (_wayBillInfos  = new List<WayBillInfo>()); }
            protected set { _wayBillInfos  = value; }
        }
    
    }
}
