//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Entity
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using LighTake.Infrastructure.Seedwork;
    
    public partial class ApplicationInfo : Entity
    {
        public virtual int ApplicationID { get; set; }
        public virtual Nullable<int> CustomerOrderID { get; set; }
        public virtual string WayBillNumber { get; set; }
        public virtual string ApplicationName { get; set; }
        public virtual Nullable<int> Qty { get; set; }
        public virtual Nullable<decimal> UnitWeight { get; set; }
        public virtual Nullable<decimal> UnitPrice { get; set; }
        public virtual Nullable<decimal> Total { get; set; }
        public virtual string HSCode { get; set; }
        public virtual bool IsDelete { get; set; }
        public virtual Nullable<System.DateTime> CreatedOn { get; set; }
        public virtual string CreatedBy { get; set; }
        public virtual Nullable<System.DateTime> LastUpdatedOn { get; set; }
        public virtual string LastUpdatedBy { get; set; }
        public virtual string PickingName { get; set; }
        public virtual string Remark { get; set; }
        public virtual string ProductUrl { get; set; }
    
        public virtual CustomerOrderInfo CustomerOrderInfo { get; set; }
        public virtual WayBillInfo WayBillInfo { get; set; }
    }
}
