//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Entity
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using LighTake.Infrastructure.Seedwork;
    
    public partial class Country : Entity
    {
    
        ICollection<MouthCountry> _mouthCountries;
    
    
        public virtual string CountryCode { get; set; }
        public virtual string Name { get; set; }
        public virtual bool AllowsShipping { get; set; }
        public virtual string ThreeLetterISOCode { get; set; }
        public virtual int NumericISOCode { get; set; }
        public virtual byte Status { get; set; }
        public virtual int DisplayOrder { get; set; }
        public virtual string ChineseName { get; set; }
    
        public virtual ICollection<MouthCountry> MouthCountries 
    	{
            get { return _mouthCountries  ?? (_mouthCountries  = new List<MouthCountry>()); }
            protected set { _mouthCountries  = value; }
        }
    
    }
}
