//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Entity
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using LighTake.Infrastructure.Seedwork;
    
    public partial class CustomerCreditInfo : Entity
    {
        public virtual int ID { get; set; }
        public virtual Nullable<int> RechargeType { get; set; }
        public virtual string VoucherPath { get; set; }
        public virtual string TransactionNo { get; set; }
        public virtual Nullable<decimal> Amount { get; set; }
        public virtual int Status { get; set; }
        public virtual string Remark { get; set; }
        public virtual System.DateTime CreatedOn { get; set; }
        public virtual string CreatedBy { get; set; }
        public virtual System.DateTime LastUpdatedOn { get; set; }
        public virtual string LastUpdatedBy { get; set; }
        public virtual Nullable<System.Guid> CustomerID { get; set; }
        public virtual string CustomerCode { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual RechargeType RechargeType1 { get; set; }
    }
}
