//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Entity
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using LighTake.Infrastructure.Seedwork;
    
    public partial class Customer : Entity
    {
    
        ICollection<CustomerAmountRecord> _customerAmountRecords;
        ICollection<CustomerCreditInfo> _customerCreditInfos;
    
    
        public virtual System.Guid CustomerID { get; set; }
        public virtual string CustomerCode { get; set; }
        public virtual string AccountID { get; set; }
        public virtual string AccountPassWord { get; set; }
        public virtual Nullable<int> CustomerTypeID { get; set; }
        public virtual string Name { get; set; }
        public virtual string EnName { get; set; }
        public virtual string LinkMan { get; set; }
        public virtual string WebSite { get; set; }
        public virtual Nullable<int> PaymentTypeID { get; set; }
        public virtual string Address { get; set; }
        public virtual string EnAddress { get; set; }
        public virtual string Country { get; set; }
        public virtual string City { get; set; }
        public virtual string Province { get; set; }
        public virtual string Tele { get; set; }
        public virtual string Mobile { get; set; }
        public virtual string Email { get; set; }
        public virtual string Fax { get; set; }
        public virtual string PostCode { get; set; }
        public virtual string QQ { get; set; }
        public virtual string MSN { get; set; }
        public virtual string Skype { get; set; }
        public virtual int Status { get; set; }
        public virtual string LastLoginIP { get; set; }
        public virtual Nullable<int> LoginCount { get; set; }
        public virtual bool EnableCredit { get; set; }
        public virtual decimal MaxDelinquentAmounts { get; set; }
        public virtual string Remark { get; set; }
        public virtual System.DateTime CreatedOn { get; set; }
        public virtual string CreatedBy { get; set; }
        public virtual System.DateTime LastUpdatedOn { get; set; }
        public virtual string LastUpdatedBy { get; set; }
        public virtual string ApiKey { get; set; }
        public virtual string ApiSecret { get; set; }
        public virtual string CustomerManager { get; set; }
    
        public virtual ICollection<CustomerAmountRecord> CustomerAmountRecords 
    	{
            get { return _customerAmountRecords  ?? (_customerAmountRecords  = new List<CustomerAmountRecord>()); }
            protected set { _customerAmountRecords  = value; }
        }
    
        public virtual ICollection<CustomerCreditInfo> CustomerCreditInfos 
    	{
            get { return _customerCreditInfos  ?? (_customerCreditInfos  = new List<CustomerCreditInfo>()); }
            protected set { _customerCreditInfos  = value; }
        }
    
        public virtual PaymentType PaymentType { get; set; }
        public virtual CustomerBalance CustomerBalance { get; set; }
    }
}
