//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Entity
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using LighTake.Infrastructure.Seedwork;
    
    public partial class DeliveryFee : Entity
    {
    
        ICollection<DeliveryFeeInfo> _deliveryFeeInfos;
    
    
        public virtual int DeliveryFeeID { get; set; }
        public virtual string WayBillNumber { get; set; }
        public virtual string CustomerOrderNumber { get; set; }
        public virtual string Trackingnumber { get; set; }
        public virtual string VenderName { get; set; }
        public virtual string VenderCode { get; set; }
        public virtual Nullable<int> VenderId { get; set; }
        public virtual int ShippingmethodID { get; set; }
        public virtual string ShippingmethodName { get; set; }
        public virtual Nullable<decimal> SetWeight { get; set; }
        public virtual Nullable<decimal> AprroveWeight { get; set; }
        public virtual int Status { get; set; }
        public virtual string Remark { get; set; }
        public virtual string Auditor { get; set; }
        public virtual Nullable<System.DateTime> AuditorDate { get; set; }
        public virtual System.DateTime CreatedOn { get; set; }
        public virtual string CreatedBy { get; set; }
        public virtual System.DateTime LastUpdatedOn { get; set; }
        public virtual string LastUpdatedBy { get; set; }
        public virtual bool IsNoGet { get; set; }
    
        public virtual ICollection<DeliveryFeeInfo> DeliveryFeeInfos 
    	{
            get { return _deliveryFeeInfos  ?? (_deliveryFeeInfos  = new List<DeliveryFeeInfo>()); }
            protected set { _deliveryFeeInfos  = value; }
        }
    
        public virtual WayBillInfo WayBillInfo { get; set; }
    }
}
