//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Entity
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using LighTake.Infrastructure.Seedwork;
    
    public partial class DeliveryChannelConfiguration : Entity
    {
        public virtual int DeliveryChannelConfigurationId { get; set; }
        public virtual int InShippingMethodId { get; set; }
        public virtual string InShippingMethodName { get; set; }
        public virtual int VenderId { get; set; }
        public virtual string VenderName { get; set; }
        public virtual int OutShippingMethodId { get; set; }
        public virtual string OutShippingMethodName { get; set; }
        public virtual System.DateTime CreatedOn { get; set; }
        public virtual string CreatedBy { get; set; }
    }
}
