//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Entity
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using LighTake.Infrastructure.Seedwork;
    
    public partial class DictionaryType : Entity
    {
        public virtual string DicTypeId { get; set; }
        public virtual string Name { get; set; }
        public virtual string EnglishName { get; set; }
        public virtual string ParentId { get; set; }
        public virtual string SpecialName { get; set; }
        public virtual string Remark { get; set; }
        public virtual int Sort { get; set; }
        public virtual bool IsParent { get; set; }
        public virtual bool IsEnable { get; set; }
        public virtual bool IsDelete { get; set; }
        public virtual System.DateTime CreatedOn { get; set; }
        public virtual string CreatedBy { get; set; }
        public virtual System.DateTime LastUpdatedOn { get; set; }
        public virtual string LastUpdatedBy { get; set; }
    }
}
