//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Entity
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using LighTake.Infrastructure.Seedwork;
    
    public partial class ExpressAccountInfo : Entity
    {
        public virtual int Id { get; set; }
        public virtual string Account { get; set; }
        public virtual string Password { get; set; }
        public virtual string ShipperAccountNumber { get; set; }
        public virtual string ServerUrl { get; set; }
        public virtual string CompanyName { get; set; }
        public virtual string Address { get; set; }
        public virtual string City { get; set; }
        public virtual string CountryCode { get; set; }
        public virtual string CountryName { get; set; }
        public virtual string PostalCode { get; set; }
        public virtual string DivisionCode { get; set; }
        public virtual string PersonName { get; set; }
        public virtual string PhoneNumber { get; set; }
        public virtual string PhoneExtension { get; set; }
        public virtual string Telex { get; set; }
        public virtual string FaxNumber { get; set; }
        public virtual string Origin { get; set; }
        public virtual string ShippingTaxId { get; set; }
        public virtual Nullable<int> ShippingMethodId { get; set; }
        public virtual string VenderCode { get; set; }
        public virtual System.DateTime CreatedOn { get; set; }
        public virtual string CreatedBy { get; set; }
        public virtual System.DateTime LastUpdatedOn { get; set; }
        public virtual string LastUpdatedBy { get; set; }
    }
}
