//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Entity
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using LighTake.Infrastructure.Seedwork;
    
    public partial class ExpressRespons : Entity
    {
        public virtual string WayBillNumber { get; set; }
        public virtual string ServiceAreaCode { get; set; }
        public virtual string FacilityCode { get; set; }
        public virtual Nullable<System.DateTime> ShipmentDetailTime { get; set; }
        public virtual string AirwayBillNumber { get; set; }
        public virtual string AirwayBillNumberBarCodeImg { get; set; }
        public virtual string DHLRoutingDataId { get; set; }
        public virtual string DHLRoutingBarCode { get; set; }
        public virtual string DHLRoutingBarCodeImg { get; set; }
        public virtual string DataIdentifier { get; set; }
        public virtual string LicensePlate { get; set; }
        public virtual string LicensePlateBarCodeImg { get; set; }
        public virtual System.DateTime CreatedOn { get; set; }
        public virtual string CreatedBy { get; set; }
        public virtual System.DateTime LastUpdatedOn { get; set; }
        public virtual string LastUpdatedBy { get; set; }
    
        public virtual WayBillInfo WayBillInfo { get; set; }
    }
}
