//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Entity
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using LighTake.Infrastructure.Seedwork;
    
    public partial class FeeType : Entity
    {
    
        ICollection<CustomerAmountRecord> _customerAmountRecords;
        ICollection<DeliveryFeeInfo> _deliveryFeeInfos;
        ICollection<ReceivingExpenseInfo> _receivingExpenseInfos;
    
    
        public virtual int FeeTypeID { get; set; }
        public virtual string FeeTypeName { get; set; }
        public virtual string CalculateExpression { get; set; }
        public virtual bool IsEnable { get; set; }
        public virtual string FeeTypeRemark { get; set; }
    
        public virtual ICollection<CustomerAmountRecord> CustomerAmountRecords 
    	{
            get { return _customerAmountRecords  ?? (_customerAmountRecords  = new List<CustomerAmountRecord>()); }
            protected set { _customerAmountRecords  = value; }
        }
    
        public virtual ICollection<DeliveryFeeInfo> DeliveryFeeInfos 
    	{
            get { return _deliveryFeeInfos  ?? (_deliveryFeeInfos  = new List<DeliveryFeeInfo>()); }
            protected set { _deliveryFeeInfos  = value; }
        }
    
        public virtual ICollection<ReceivingExpenseInfo> ReceivingExpenseInfos 
    	{
            get { return _receivingExpenseInfos  ?? (_receivingExpenseInfos  = new List<ReceivingExpenseInfo>()); }
            protected set { _receivingExpenseInfos  = value; }
        }
    
    }
}
