//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Entity
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using LighTake.Infrastructure.Seedwork;
    
    public partial class FuzhouPostLog : Entity
    {
        public virtual int ID { get; set; }
        public virtual string WayBillNumber { get; set; }
        public virtual int Status { get; set; }
        public virtual Nullable<int> OutShippingMethodID { get; set; }
        public virtual string ErrorNumber { get; set; }
        public virtual System.DateTime CreateOn { get; set; }
        public virtual System.DateTime LastUpdateOn { get; set; }
    }
}
