//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Entity
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using LighTake.Infrastructure.Seedwork;
    
    public partial class InStorageOrSettlementRelational : Entity
    {
        public virtual int ID { get; set; }
        public virtual string SettlementNumber { get; set; }
        public virtual string InStorageID { get; set; }
    
        public virtual InStorageInfo InStorageInfo { get; set; }
        public virtual SettlementInfo SettlementInfo { get; set; }
    }
}
