//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Entity
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using LighTake.Infrastructure.Seedwork;
    
    public partial class InsuredCalculation : Entity
    {
    
        ICollection<CustomerOrderInfo> _customerOrderInfos;
        ICollection<WayBillInfo> _wayBillInfos;
    
    
        public virtual int InsuredID { get; set; }
        public virtual string InsuredName { get; set; }
        public virtual string InsuredCalculation1 { get; set; }
        public virtual Nullable<int> Status { get; set; }
        public virtual Nullable<System.DateTime> CreatedOn { get; set; }
        public virtual string CreatedBy { get; set; }
        public virtual Nullable<System.DateTime> LastUpdatedOn { get; set; }
        public virtual string LastUpdatedBy { get; set; }
    
        public virtual ICollection<CustomerOrderInfo> CustomerOrderInfos 
    	{
            get { return _customerOrderInfos  ?? (_customerOrderInfos  = new List<CustomerOrderInfo>()); }
            protected set { _customerOrderInfos  = value; }
        }
    
        public virtual ICollection<WayBillInfo> WayBillInfos 
    	{
            get { return _wayBillInfos  ?? (_wayBillInfos  = new List<WayBillInfo>()); }
            protected set { _wayBillInfos  = value; }
        }
    
    }
}
