//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Entity
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using LighTake.Infrastructure.Seedwork;
    
    public partial class InTackingLogInfo : Entity
    {
        public virtual long ID { get; set; }
        public virtual string WaybillNumber { get; set; }
        public virtual Nullable<System.DateTime> ProcessDate { get; set; }
        public virtual string ProcessContent { get; set; }
        public virtual string ProcessLocation { get; set; }
        public virtual Nullable<System.DateTime> CreatedOn { get; set; }
        public virtual string CreatedBy { get; set; }
        public virtual Nullable<System.DateTime> LastUpdatedOn { get; set; }
        public virtual string LastUpdatedBy { get; set; }
        public virtual string Remarks { get; set; }
    }
}
