//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Entity
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using LighTake.Infrastructure.Seedwork;
    
    public partial class MailTotalPackageInfo : Entity
    {
    
        ICollection<MailTotalPackageOrPostBagRelational> _mailTotalPackageOrPostBagRelationals;
    
    
        public virtual string MailTotalPackageNumber { get; set; }
        public virtual string TotalPackageNumber { get; set; }
        public virtual System.DateTime ScanTime { get; set; }
        public virtual string FZFlightNo { get; set; }
        public virtual Nullable<System.DateTime> FuZhouDepartureTime { get; set; }
        public virtual Nullable<System.DateTime> TaiWanArrivedTime { get; set; }
        public virtual string TWFlightNo { get; set; }
        public virtual Nullable<System.DateTime> TaiWanDepartureTime { get; set; }
        public virtual Nullable<System.DateTime> ToArrivedTime { get; set; }
        public virtual System.DateTime CreatedOn { get; set; }
        public virtual string CreatedBy { get; set; }
        public virtual System.DateTime LastUpdatedOn { get; set; }
        public virtual string LastUpdatedBy { get; set; }
        public virtual int TrackStatus { get; set; }
        public virtual int ShortNumber { get; set; }
        public virtual Nullable<int> FZFlightType { get; set; }
    
        public virtual ICollection<MailTotalPackageOrPostBagRelational> MailTotalPackageOrPostBagRelationals 
    	{
            get { return _mailTotalPackageOrPostBagRelationals  ?? (_mailTotalPackageOrPostBagRelationals  = new List<MailTotalPackageOrPostBagRelational>()); }
            protected set { _mailTotalPackageOrPostBagRelationals  = value; }
        }
    
    }
}
