//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Entity
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using LighTake.Infrastructure.Seedwork;
    
    public partial class MoneyChangeTypeInfo : Entity
    {
    
        ICollection<CustomerAmountRecord> _customerAmountRecords;
        ICollection<DeliveryFeeInfo> _deliveryFeeInfos;
    
    
        public virtual int MoneyChangeTypeID { get; set; }
        public virtual string MoneyChangeTypeShortName { get; set; }
        public virtual string MoneyChangeTypeName { get; set; }
        public virtual bool MoneyFlow { get; set; }
        public virtual string Remark { get; set; }
        public virtual int Status { get; set; }
    
        public virtual ICollection<CustomerAmountRecord> CustomerAmountRecords 
    	{
            get { return _customerAmountRecords  ?? (_customerAmountRecords  = new List<CustomerAmountRecord>()); }
            protected set { _customerAmountRecords  = value; }
        }
    
        public virtual ICollection<DeliveryFeeInfo> DeliveryFeeInfos 
    	{
            get { return _deliveryFeeInfos  ?? (_deliveryFeeInfos  = new List<DeliveryFeeInfo>()); }
            protected set { _deliveryFeeInfos  = value; }
        }
    
    }
}
