//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Entity
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using LighTake.Infrastructure.Seedwork;
    
    public partial class OutStorageInfo : Entity
    {
    
        ICollection<MailPostBagInfo> _mailPostBagInfos;
        ICollection<WayBillInfo> _wayBillInfos;
    
    
        public virtual string OutStorageID { get; set; }
        public virtual string DeliveryStaff { get; set; }
        public virtual string VenderCode { get; set; }
        public virtual string VenderName { get; set; }
        public virtual Nullable<decimal> TotalWeight { get; set; }
        public virtual Nullable<int> TotalQty { get; set; }
        public virtual Nullable<decimal> TotalFee { get; set; }
        public virtual Nullable<decimal> Freight { get; set; }
        public virtual Nullable<decimal> Register { get; set; }
        public virtual Nullable<decimal> FuelCharge { get; set; }
        public virtual Nullable<decimal> Surcharge { get; set; }
        public virtual int Status { get; set; }
        public virtual System.DateTime CreatedOn { get; set; }
        public virtual string CreatedBy { get; set; }
        public virtual System.DateTime LastUpdatedOn { get; set; }
        public virtual string LastUpdatedBy { get; set; }
        public virtual string Remark { get; set; }
        public virtual Nullable<int> GoodsTypeID { get; set; }
    
        public virtual GoodsTypeInfo GoodsTypeInfo { get; set; }
        public virtual ICollection<MailPostBagInfo> MailPostBagInfos 
    	{
            get { return _mailPostBagInfos  ?? (_mailPostBagInfos  = new List<MailPostBagInfo>()); }
            protected set { _mailPostBagInfos  = value; }
        }
    
        public virtual ICollection<WayBillInfo> WayBillInfos 
    	{
            get { return _wayBillInfos  ?? (_wayBillInfos  = new List<WayBillInfo>()); }
            protected set { _wayBillInfos  = value; }
        }
    
    }
}
