//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Entity
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using LighTake.Infrastructure.Seedwork;
    
    public partial class PaymentType : Entity
    {
    
        ICollection<Customer> _customers;
    
    
        public virtual int PaymentTypeID { get; set; }
        public virtual string PaymentName { get; set; }
        public virtual string Remark { get; set; }
        public virtual int Status { get; set; }
        public virtual System.DateTime CreatedOn { get; set; }
        public virtual string CreatedBy { get; set; }
        public virtual System.DateTime LastUpdatedOn { get; set; }
        public virtual string LastUpdatedBy { get; set; }
    
        public virtual ICollection<Customer> Customers 
    	{
            get { return _customers  ?? (_customers  = new List<Customer>()); }
            protected set { _customers  = value; }
        }
    
    }
}
