//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Entity
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using LighTake.Infrastructure.Seedwork;
    
    public partial class ReceivingBill : Entity
    {
        public virtual string ReceivingBillID { get; set; }
        public virtual string CustomerCode { get; set; }
        public virtual string CustomerName { get; set; }
        public virtual Nullable<System.DateTime> ReceivingBillDate { get; set; }
        public virtual string ReceivingBillAuditor { get; set; }
        public virtual Nullable<System.DateTime> BillStartTime { get; set; }
        public virtual Nullable<System.DateTime> BillEndTime { get; set; }
        public virtual Nullable<int> ShippingMethodID { get; set; }
        public virtual string CountryCode { get; set; }
        public virtual Nullable<int> Search { get; set; }
        public virtual string SearchValue { get; set; }
        public virtual int Status { get; set; }
        public virtual string JobRemark { get; set; }
    }
}
