//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Entity
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using LighTake.Infrastructure.Seedwork;
    
    public partial class ReceivingExpenseInfo : Entity
    {
        public virtual int ReceivingExpenseInfoID { get; set; }
        public virtual Nullable<int> ReceivingExpenseID { get; set; }
        public virtual Nullable<int> FeeTypeID { get; set; }
        public virtual Nullable<decimal> Amount { get; set; }
        public virtual int OperationType { get; set; }
        public virtual System.DateTime CreatedOn { get; set; }
        public virtual string CreatedBy { get; set; }
        public virtual System.DateTime LastUpdatedOn { get; set; }
        public virtual string LastUpdatedBy { get; set; }
        public virtual string ReceivingBillID { get; set; }
    
        public virtual FeeType FeeType { get; set; }
        public virtual ReceivingExpens ReceivingExpens { get; set; }
    }
}
