//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Entity
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using LighTake.Infrastructure.Seedwork;
    
    public partial class RechargeType : Entity
    {
    
        ICollection<CustomerCreditInfo> _customerCreditInfos;
    
    
        public virtual int RechargeType1 { get; set; }
        public virtual string RechargeTypeName { get; set; }
        public virtual int Status { get; set; }
        public virtual System.DateTime CreatedOn { get; set; }
        public virtual string CreatedBy { get; set; }
        public virtual System.DateTime LastUpdatedOn { get; set; }
        public virtual string LastUpdatedBy { get; set; }
    
        public virtual ICollection<CustomerCreditInfo> CustomerCreditInfos 
    	{
            get { return _customerCreditInfos  ?? (_customerCreditInfos  = new List<CustomerCreditInfo>()); }
            protected set { _customerCreditInfos  = value; }
        }
    
    }
}
