//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Entity
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using LighTake.Infrastructure.Seedwork;
    
    public partial class ReturnGoods : Entity
    {
        public virtual string ReGoodsId { get; set; }
        public virtual string WayBillNumber { get; set; }
        public virtual decimal Weight { get; set; }
        public virtual int Type { get; set; }
        public virtual string Reason { get; set; }
        public virtual string ReasonRemark { get; set; }
        public virtual bool IsReturnShipping { get; set; }
        public virtual System.DateTime CreatedOn { get; set; }
        public virtual string CreatedBy { get; set; }
        public virtual System.DateTime LastUpdatedOn { get; set; }
        public virtual string LastUpdatedBy { get; set; }
        public virtual decimal ShippingFee { get; set; }
        public virtual int Status { get; set; }
        public virtual string Auditor { get; set; }
        public virtual Nullable<System.DateTime> AuditorDate { get; set; }
        public virtual int ReturnSource { get; set; }
    
        public virtual WayBillInfo WayBillInfo { get; set; }
    }
}
