//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Entity
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using LighTake.Infrastructure.Seedwork;
    
    public partial class SequenceNumber : Entity
    {
        public virtual int ID { get; set; }
        public virtual string Code { get; set; }
        public virtual string Prefix { get; set; }
        public virtual string DateType { get; set; }
        public virtual string Infix { get; set; }
        public virtual Nullable<int> IndexLength { get; set; }
        public virtual string Suffix { get; set; }
        public virtual string MaxDate { get; set; }
        public virtual Nullable<int> MaxIndex { get; set; }
        public virtual string CurrentMaxValue { get; set; }
    }
}
