//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Entity
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using LighTake.Infrastructure.Seedwork;
    
    public partial class SettlementInfo : Entity
    {
    
        ICollection<InStorageOrSettlementRelational> _inStorageOrSettlementRelationals;
        ICollection<SettlementDetailsInfo> _settlementDetailsInfos;
    
    
        public virtual string SettlementNumber { get; set; }
        public virtual string CustomerCode { get; set; }
        public virtual int TotalNumber { get; set; }
        public virtual decimal TotalWeight { get; set; }
        public virtual decimal TotalSettleWeight { get; set; }
        public virtual decimal TotalFee { get; set; }
        public virtual int Status { get; set; }
        public virtual string SalesMan { get; set; }
        public virtual string SalesManTel { get; set; }
        public virtual string SettlementBy { get; set; }
        public virtual Nullable<System.DateTime> SettlementOn { get; set; }
        public virtual string CreatedBy { get; set; }
        public virtual System.DateTime CreatedOn { get; set; }
        public virtual string LastUpdatedBy { get; set; }
        public virtual System.DateTime LastUpdatedOn { get; set; }
    
        public virtual ICollection<InStorageOrSettlementRelational> InStorageOrSettlementRelationals 
    	{
            get { return _inStorageOrSettlementRelationals  ?? (_inStorageOrSettlementRelationals  = new List<InStorageOrSettlementRelational>()); }
            protected set { _inStorageOrSettlementRelationals  = value; }
        }
    
        public virtual ICollection<SettlementDetailsInfo> SettlementDetailsInfos 
    	{
            get { return _settlementDetailsInfos  ?? (_settlementDetailsInfos  = new List<SettlementDetailsInfo>()); }
            protected set { _settlementDetailsInfos  = value; }
        }
    
    }
}
