//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Entity
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using LighTake.Infrastructure.Seedwork;
    
    public partial class ShippingInfo : Entity
    {
    
        ICollection<CustomerOrderInfo> _customerOrderInfos;
        ICollection<WayBillInfo> _wayBillInfos;
    
    
        public virtual int ShippingInfoID { get; set; }
        public virtual string CountryCode { get; set; }
        public virtual string ShippingFirstName { get; set; }
        public virtual string ShippingLastName { get; set; }
        public virtual string ShippingCompany { get; set; }
        public virtual string ShippingAddress { get; set; }
        public virtual string ShippingCity { get; set; }
        public virtual string ShippingState { get; set; }
        public virtual string ShippingZip { get; set; }
        public virtual string ShippingPhone { get; set; }
        public virtual string ShippingTaxId { get; set; }
        public virtual string ShippingAddress1 { get; set; }
        public virtual string ShippingAddress2 { get; set; }
    
        public virtual ICollection<CustomerOrderInfo> CustomerOrderInfos 
    	{
            get { return _customerOrderInfos  ?? (_customerOrderInfos  = new List<CustomerOrderInfo>()); }
            protected set { _customerOrderInfos  = value; }
        }
    
        public virtual ICollection<WayBillInfo> WayBillInfos 
    	{
            get { return _wayBillInfos  ?? (_wayBillInfos  = new List<WayBillInfo>()); }
            protected set { _wayBillInfos  = value; }
        }
    
    }
}
