//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Entity
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using LighTake.Infrastructure.Seedwork;
    
    public partial class TrackingNumberInfo : Entity
    {
    
        ICollection<TrackingNumberDetailInfo> _trackingNumberDetailInfos;
    
    
        public virtual string TrackingNumberID { get; set; }
        public virtual int ShippingMethodID { get; set; }
        public virtual string ApplianceCountry { get; set; }
        public virtual string StartSegment { get; set; }
        public virtual string EndSegment { get; set; }
        public virtual string StartCharacter { get; set; }
        public virtual string EndCharacter { get; set; }
        public virtual short Status { get; set; }
        public virtual string Remarks { get; set; }
        public virtual string CreatedBy { get; set; }
        public virtual System.DateTime CreatedNo { get; set; }
        public virtual string LastUpdatedBy { get; set; }
        public virtual System.DateTime LastUpdateOn { get; set; }
    
        public virtual ICollection<TrackingNumberDetailInfo> TrackingNumberDetailInfos 
    	{
            get { return _trackingNumberDetailInfos  ?? (_trackingNumberDetailInfos  = new List<TrackingNumberDetailInfo>()); }
            protected set { _trackingNumberDetailInfos  = value; }
        }
    
    }
}
