//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Entity
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using LighTake.Infrastructure.Seedwork;
    
    public partial class TrackingNumberDetailInfo : Entity
    {
        public virtual int TrackingNumberDetailID { get; set; }
        public virtual string TrackingNumberID { get; set; }
        public virtual string TrackingNumber { get; set; }
        public virtual short Status { get; set; }
        public virtual string WayBillNumber { get; set; }
    
        public virtual TrackingNumberInfo TrackingNumberInfo { get; set; }
    }
}
