//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Entity
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using LighTake.Infrastructure.Seedwork;
    
    public partial class WayBillEventLog : Entity
    {
        public virtual int WayBillEventLogId { get; set; }
        public virtual string WayBillNumber { get; set; }
        public virtual int EventCode { get; set; }
        public virtual System.DateTime EventDate { get; set; }
        public virtual string Operator { get; set; }
        public virtual string Description { get; set; }
        public virtual bool TrackingLogCreated { get; set; }
        public virtual Nullable<int> TrackingLogProgress { get; set; }
        public virtual System.DateTime LastUpdatedOn { get; set; }
        public virtual string Remarks { get; set; }
    }
}
