//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Express.NLPOST {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorCode {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorCode() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LMS.Data.Express.NLPOST.ErrorCode", typeof(ErrorCode).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 身份验证失败 的本地化字符串。
        /// </summary>
        public static string _9000 {
            get {
                return ResourceManager.GetString("9000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户订单号超过长度限制 的本地化字符串。
        /// </summary>
        public static string _9001 {
            get {
                return ResourceManager.GetString("9001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户订单号存在重复 的本地化字符串。
        /// </summary>
        public static string _9002 {
            get {
                return ResourceManager.GetString("9002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户订单号格式错误，只能包含数字和字母 的本地化字符串。
        /// </summary>
        public static string _9003 {
            get {
                return ResourceManager.GetString("9003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运输方式不能为空 的本地化字符串。
        /// </summary>
        public static string _9004 {
            get {
                return ResourceManager.GetString("9004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运输方式错误 的本地化字符串。
        /// </summary>
        public static string _9005 {
            get {
                return ResourceManager.GetString("9005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目的国家不能为空 的本地化字符串。
        /// </summary>
        public static string _9006 {
            get {
                return ResourceManager.GetString("9006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目的国家错误，请填写国家二字码 的本地化字符串。
        /// </summary>
        public static string _9007 {
            get {
                return ResourceManager.GetString("9007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收件人公司名超过长度限制 的本地化字符串。
        /// </summary>
        public static string _9008 {
            get {
                return ResourceManager.GetString("9008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收件人姓名不能为空 的本地化字符串。
        /// </summary>
        public static string _9009 {
            get {
                return ResourceManager.GetString("9009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收件人姓名超过长度限制 的本地化字符串。
        /// </summary>
        public static string _9010 {
            get {
                return ResourceManager.GetString("9010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收件人州或省超过长度限制 的本地化字符串。
        /// </summary>
        public static string _9011 {
            get {
                return ResourceManager.GetString("9011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收件人城市超过长度限制 的本地化字符串。
        /// </summary>
        public static string _9012 {
            get {
                return ResourceManager.GetString("9012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联系地址不能为空 的本地化字符串。
        /// </summary>
        public static string _9013 {
            get {
                return ResourceManager.GetString("9013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联系地址超过长度限制 的本地化字符串。
        /// </summary>
        public static string _9014 {
            get {
                return ResourceManager.GetString("9014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收件人手机号码超过长度限制 的本地化字符串。
        /// </summary>
        public static string _9015 {
            get {
                return ResourceManager.GetString("9015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收件人邮编超过长度限制 的本地化字符串。
        /// </summary>
        public static string _9016 {
            get {
                return ResourceManager.GetString("9016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收件人邮编只能是英文和数字 的本地化字符串。
        /// </summary>
        public static string _9017 {
            get {
                return ResourceManager.GetString("9017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重量数字格式不准确 的本地化字符串。
        /// </summary>
        public static string _9018 {
            get {
                return ResourceManager.GetString("9018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重量必须大于 0 的本地化字符串。
        /// </summary>
        public static string _9019 {
            get {
                return ResourceManager.GetString("9019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重量超过长度限制 的本地化字符串。
        /// </summary>
        public static string _9020 {
            get {
                return ResourceManager.GetString("9020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否退件填写错误，只能填写 Y 或 N 的本地化字符串。
        /// </summary>
        public static string _9021 {
            get {
                return ResourceManager.GetString("9021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 海关申报信息不能为空 的本地化字符串。
        /// </summary>
        public static string _9022 {
            get {
                return ResourceManager.GetString("9022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 英文申报品名不能为空 的本地化字符串。
        /// </summary>
        public static string _9023 {
            get {
                return ResourceManager.GetString("9023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 英文申报品名超过长度限制 的本地化字符串。
        /// </summary>
        public static string _9024 {
            get {
                return ResourceManager.GetString("9024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 英文申报品名只能为英文、数字、空格、（）、()、，、,% 的本地化字符串。
        /// </summary>
        public static string _9025 {
            get {
                return ResourceManager.GetString("9025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 申报价值必须大于 0 的本地化字符串。
        /// </summary>
        public static string _9026 {
            get {
                return ResourceManager.GetString("9026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 申报价值必须为正数 的本地化字符串。
        /// </summary>
        public static string _9027 {
            get {
                return ResourceManager.GetString("9027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 申报价值超过长度限制 的本地化字符串。
        /// </summary>
        public static string _9028 {
            get {
                return ResourceManager.GetString("9028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 申报品数量必须为正整数 的本地化字符串。
        /// </summary>
        public static string _9029 {
            get {
                return ResourceManager.GetString("9029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 申报品数量超过长度限制 的本地化字符串。
        /// </summary>
        public static string _9030 {
            get {
                return ResourceManager.GetString("9030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中文申报品名超过长度限制 的本地化字符串。
        /// </summary>
        public static string _9031 {
            get {
                return ResourceManager.GetString("9031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中文申报品名必须为中文 的本地化字符串。
        /// </summary>
        public static string _9032 {
            get {
                return ResourceManager.GetString("9032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 海关货物编号超过长度限制 的本地化字符串。
        /// </summary>
        public static string _9033 {
            get {
                return ResourceManager.GetString("9033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 海关货物编号只能为数字 的本地化字符串。
        /// </summary>
        public static string _9034 {
            get {
                return ResourceManager.GetString("9034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收件人手机号码格式不正确 的本地化字符串。
        /// </summary>
        public static string _9035 {
            get {
                return ResourceManager.GetString("9035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务商单号或顺丰单号已用完，请联系客服人员 的本地化字符串。
        /// </summary>
        public static string _9036 {
            get {
                return ResourceManager.GetString("9036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 寄件人姓名超过长度限制 的本地化字符串。
        /// </summary>
        public static string _9037 {
            get {
                return ResourceManager.GetString("9037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 寄件人公司名超过长度限制 的本地化字符串。
        /// </summary>
        public static string _9038 {
            get {
                return ResourceManager.GetString("9038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 寄件人省超过长度限制 的本地化字符串。
        /// </summary>
        public static string _9039 {
            get {
                return ResourceManager.GetString("9039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 寄件人城市超过长度限制 的本地化字符串。
        /// </summary>
        public static string _9040 {
            get {
                return ResourceManager.GetString("9040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 寄件人地址超过长度限制 的本地化字符串。
        /// </summary>
        public static string _9041 {
            get {
                return ResourceManager.GetString("9041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 寄件人手机号码超过长度限制 的本地化字符串。
        /// </summary>
        public static string _9042 {
            get {
                return ResourceManager.GetString("9042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 寄件人手机号码格式不准确 的本地化字符串。
        /// </summary>
        public static string _9043 {
            get {
                return ResourceManager.GetString("9043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 寄件人邮编超过长度限制 的本地化字符串。
        /// </summary>
        public static string _9044 {
            get {
                return ResourceManager.GetString("9044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 寄件人邮编只能是英文和数字 的本地化字符串。
        /// </summary>
        public static string _9045 {
            get {
                return ResourceManager.GetString("9045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持批量操作 的本地化字符串。
        /// </summary>
        public static string _9046 {
            get {
                return ResourceManager.GetString("9046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批量交易记录数超过限制 的本地化字符串。
        /// </summary>
        public static string _9047 {
            get {
                return ResourceManager.GetString("9047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此订单已确认，不能再操作 的本地化字符串。
        /// </summary>
        public static string _9048 {
            get {
                return ResourceManager.GetString("9048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此订单已收货，不能再操作 的本地化字符串。
        /// </summary>
        public static string _9049 {
            get {
                return ResourceManager.GetString("9049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此订单已出货，不能再操作 的本地化字符串。
        /// </summary>
        public static string _9050 {
            get {
                return ResourceManager.GetString("9050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此订单已取消，不能再操作 的本地化字符串。
        /// </summary>
        public static string _9051 {
            get {
                return ResourceManager.GetString("9051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收件人电话超过长度限制 的本地化字符串。
        /// </summary>
        public static string _9052 {
            get {
                return ResourceManager.GetString("9052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收件人电话格式不正确 的本地化字符串。
        /// </summary>
        public static string _9053 {
            get {
                return ResourceManager.GetString("9053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 寄件人电话超过长度限制 的本地化字符串。
        /// </summary>
        public static string _9054 {
            get {
                return ResourceManager.GetString("9054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 寄件人电话格式不正确 的本地化字符串。
        /// </summary>
        public static string _9055 {
            get {
                return ResourceManager.GetString("9055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货物件数必须为正整数 的本地化字符串。
        /// </summary>
        public static string _9056 {
            get {
                return ResourceManager.GetString("9056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货物件数超过长度限制 的本地化字符串。
        /// </summary>
        public static string _9057 {
            get {
                return ResourceManager.GetString("9057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 寄件人国家错误，请填写国家二字码，默认为 CN 的本地化字符串。
        /// </summary>
        public static string _9058 {
            get {
                return ResourceManager.GetString("9058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货物单位超过长度限制，默认为 PCE 的本地化字符串。
        /// </summary>
        public static string _9059 {
            get {
                return ResourceManager.GetString("9059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货物单位重量格式不正确 的本地化字符串。
        /// </summary>
        public static string _9060 {
            get {
                return ResourceManager.GetString("9060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货物单位重量超过长度限制 的本地化字符串。
        /// </summary>
        public static string _9061 {
            get {
                return ResourceManager.GetString("9061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该运输方式暂时不支持此国家的派送，请选择其他派送方式 的本地化字符串。
        /// </summary>
        public static string _9062 {
            get {
                return ResourceManager.GetString("9062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该运输方式暂时不支持此邮编的派送，请选择其他派送方式 的本地化字符串。
        /// </summary>
        public static string _9063 {
            get {
                return ResourceManager.GetString("9063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该运输方式必须输入邮编 的本地化字符串。
        /// </summary>
        public static string _9064 {
            get {
                return ResourceManager.GetString("9064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 寄件人国家国家不能为空 的本地化字符串。
        /// </summary>
        public static string _9065 {
            get {
                return ResourceManager.GetString("9065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 寄件人公司名不能为空 的本地化字符串。
        /// </summary>
        public static string _9066 {
            get {
                return ResourceManager.GetString("9066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 寄件人公司名不能包含中文 的本地化字符串。
        /// </summary>
        public static string _9067 {
            get {
                return ResourceManager.GetString("9067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 寄件人姓名不能为空 的本地化字符串。
        /// </summary>
        public static string _9068 {
            get {
                return ResourceManager.GetString("9068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 寄件人姓名不能包含中文 的本地化字符串。
        /// </summary>
        public static string _9069 {
            get {
                return ResourceManager.GetString("9069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 寄件人城市不能为空 的本地化字符串。
        /// </summary>
        public static string _9070 {
            get {
                return ResourceManager.GetString("9070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 寄件人城市不能包含中文 的本地化字符串。
        /// </summary>
        public static string _9071 {
            get {
                return ResourceManager.GetString("9071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 寄件人地址不能为空 的本地化字符串。
        /// </summary>
        public static string _9072 {
            get {
                return ResourceManager.GetString("9072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 寄件人地址不能包含中文 的本地化字符串。
        /// </summary>
        public static string _9073 {
            get {
                return ResourceManager.GetString("9073", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 寄件人邮编不能为空 的本地化字符串。
        /// </summary>
        public static string _9074 {
            get {
                return ResourceManager.GetString("9074", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 寄件人邮编不能包含中文 的本地化字符串。
        /// </summary>
        public static string _9075 {
            get {
                return ResourceManager.GetString("9075", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收件人公司名不能为空 的本地化字符串。
        /// </summary>
        public static string _9076 {
            get {
                return ResourceManager.GetString("9076", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收件人公司名不能包含中文 的本地化字符串。
        /// </summary>
        public static string _9077 {
            get {
                return ResourceManager.GetString("9077", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收件人城市不能为空 的本地化字符串。
        /// </summary>
        public static string _9078 {
            get {
                return ResourceManager.GetString("9078", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收件人城市不能包含中文 的本地化字符串。
        /// </summary>
        public static string _9079 {
            get {
                return ResourceManager.GetString("9079", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询类别不正确，合法值为：1（运单号），2（订单号） 的本地化字符串。
        /// </summary>
        public static string _9080 {
            get {
                return ResourceManager.GetString("9080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询号不能不能为空。 的本地化字符串。
        /// </summary>
        public static string _9081 {
            get {
                return ResourceManager.GetString("9081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询方法错误，合法值为：1（标准查询） 的本地化字符串。
        /// </summary>
        public static string _9082 {
            get {
                return ResourceManager.GetString("9082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询号不能超过 10 个。注：多个单号，以逗号分隔。 的本地化字符串。
        /// </summary>
        public static string _9083 {
            get {
                return ResourceManager.GetString("9083", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收件人电话不能为空 的本地化字符串。
        /// </summary>
        public static string _9084 {
            get {
                return ResourceManager.GetString("9084", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收件人姓名不能包含中文 的本地化字符串。
        /// </summary>
        public static string _9085 {
            get {
                return ResourceManager.GetString("9085", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 英文申报品名必须为英文 的本地化字符串。
        /// </summary>
        public static string _9086 {
            get {
                return ResourceManager.GetString("9086", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收件人手机不能包含中文 的本地化字符串。
        /// </summary>
        public static string _9087 {
            get {
                return ResourceManager.GetString("9087", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收件人电话不能包含中文 的本地化字符串。
        /// </summary>
        public static string _9088 {
            get {
                return ResourceManager.GetString("9088", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 寄件人电话不能包含中文 的本地化字符串。
        /// </summary>
        public static string _9089 {
            get {
                return ResourceManager.GetString("9089", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 寄件人手机不能包含中文 的本地化字符串。
        /// </summary>
        public static string _9090 {
            get {
                return ResourceManager.GetString("9090", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 海关货物编号不能为空 的本地化字符串。
        /// </summary>
        public static string _9091 {
            get {
                return ResourceManager.GetString("9091", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联系地址不能包含中文 的本地化字符串。
        /// </summary>
        public static string _9092 {
            get {
                return ResourceManager.GetString("9092", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当总申报价值超过 75 欧元时【收件人邮箱】不能为空 的本地化字符串。
        /// </summary>
        public static string _9093 {
            get {
                return ResourceManager.GetString("9093", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收件人邮箱超过长度限制 的本地化字符串。
        /// </summary>
        public static string _9094 {
            get {
                return ResourceManager.GetString("9094", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收件人邮箱格式不正确 的本地化字符串。
        /// </summary>
        public static string _9095 {
            get {
                return ResourceManager.GetString("9095", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 寄件人省不能包含中文 的本地化字符串。
        /// </summary>
        public static string _9096 {
            get {
                return ResourceManager.GetString("9096", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收件人邮编不能包含中文 的本地化字符串。
        /// </summary>
        public static string _9098 {
            get {
                return ResourceManager.GetString("9098", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 英文申报品名根据服务商要求，申报品名包含disc、speaker、power bank、battery、magne禁止运输，请选择其他运输方式！ 的本地化字符串。
        /// </summary>
        public static string _9099 {
            get {
                return ResourceManager.GetString("9099", resourceCulture);
            }
        }
    }
}
