//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Services.UserServices.PMSServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserLoginInfo", Namespace="http://schemas.datacontract.org/2004/07/PMS.WcfService")]
    [System.SerializableAttribute()]
    public partial class UserLoginInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SystemCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SystemCode {
            get {
                return this.SystemCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SystemCodeField, value) != true)) {
                    this.SystemCodeField = value;
                    this.RaisePropertyChanged("SystemCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/PMS.WcfService")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LMS.Services.UserServices.PMSServiceReference.PermissionsResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LMS.Services.UserServices.PMSServiceReference.UserLoginResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LMS.Services.UserServices.PMSServiceReference.UserLoginInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LMS.Services.UserServices.PMSServiceReference.UserInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LMS.Services.UserServices.PMSServiceReference.PermissionModule[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LMS.Services.UserServices.PMSServiceReference.PermissionModule))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LMS.Services.UserServices.PMSServiceReference.UserBaseInfo))]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PermissionsResponse", Namespace="http://schemas.datacontract.org/2004/07/PMS.WcfService.Common")]
    [System.SerializableAttribute()]
    public partial class PermissionsResponse : LMS.Services.UserServices.PMSServiceReference.Response {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LMS.Services.UserServices.PMSServiceReference.PermissionModule[] PermissionsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LMS.Services.UserServices.PMSServiceReference.PermissionModule[] Permissions {
            get {
                return this.PermissionsField;
            }
            set {
                if ((object.ReferenceEquals(this.PermissionsField, value) != true)) {
                    this.PermissionsField = value;
                    this.RaisePropertyChanged("Permissions");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserLoginResponse", Namespace="http://schemas.datacontract.org/2004/07/PMS.WcfService")]
    [System.SerializableAttribute()]
    public partial class UserLoginResponse : LMS.Services.UserServices.PMSServiceReference.Response {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LMS.Services.UserServices.PMSServiceReference.UserInfo UserInfoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LMS.Services.UserServices.PMSServiceReference.UserInfo UserInfo {
            get {
                return this.UserInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.UserInfoField, value) != true)) {
                    this.UserInfoField = value;
                    this.RaisePropertyChanged("UserInfo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserInfo", Namespace="http://schemas.datacontract.org/2004/07/PMS.WcfService")]
    [System.SerializableAttribute()]
    public partial class UserInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LMS.Services.UserServices.PMSServiceReference.PermissionModule[] PermissionListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LMS.Services.UserServices.PMSServiceReference.UserBaseInfo UserBaseInfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LMS.Services.UserServices.PMSServiceReference.PermissionModule[] PermissionList {
            get {
                return this.PermissionListField;
            }
            set {
                if ((object.ReferenceEquals(this.PermissionListField, value) != true)) {
                    this.PermissionListField = value;
                    this.RaisePropertyChanged("PermissionList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LMS.Services.UserServices.PMSServiceReference.UserBaseInfo UserBaseInfo {
            get {
                return this.UserBaseInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.UserBaseInfoField, value) != true)) {
                    this.UserBaseInfoField = value;
                    this.RaisePropertyChanged("UserBaseInfo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PermissionModule", Namespace="http://schemas.datacontract.org/2004/07/PMS.WcfService")]
    [System.SerializableAttribute()]
    public partial class PermissionModule : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsBottomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsMenuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ModuleIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NavigateUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ParentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SortCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsBottom {
            get {
                return this.IsBottomField;
            }
            set {
                if ((this.IsBottomField.Equals(value) != true)) {
                    this.IsBottomField = value;
                    this.RaisePropertyChanged("IsBottom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsMenu {
            get {
                return this.IsMenuField;
            }
            set {
                if ((this.IsMenuField.Equals(value) != true)) {
                    this.IsMenuField = value;
                    this.RaisePropertyChanged("IsMenu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Level {
            get {
                return this.LevelField;
            }
            set {
                if ((this.LevelField.Equals(value) != true)) {
                    this.LevelField = value;
                    this.RaisePropertyChanged("Level");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ModuleID {
            get {
                return this.ModuleIDField;
            }
            set {
                if ((this.ModuleIDField.Equals(value) != true)) {
                    this.ModuleIDField = value;
                    this.RaisePropertyChanged("ModuleID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NavigateUrl {
            get {
                return this.NavigateUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.NavigateUrlField, value) != true)) {
                    this.NavigateUrlField = value;
                    this.RaisePropertyChanged("NavigateUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParentID {
            get {
                return this.ParentIDField;
            }
            set {
                if ((this.ParentIDField.Equals(value) != true)) {
                    this.ParentIDField = value;
                    this.RaisePropertyChanged("ParentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SortCode {
            get {
                return this.SortCodeField;
            }
            set {
                if ((this.SortCodeField.Equals(value) != true)) {
                    this.SortCodeField = value;
                    this.RaisePropertyChanged("SortCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserBaseInfo", Namespace="http://schemas.datacontract.org/2004/07/PMS.WcfService")]
    [System.SerializableAttribute()]
    public partial class UserBaseInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BirthdayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CompanyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DutyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IPAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuperAdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OICQField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RealNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> RoleIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SystemCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Birthday {
            get {
                return this.BirthdayField;
            }
            set {
                if ((object.ReferenceEquals(this.BirthdayField, value) != true)) {
                    this.BirthdayField = value;
                    this.RaisePropertyChanged("Birthday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CompanyID {
            get {
                return this.CompanyIDField;
            }
            set {
                if ((this.CompanyIDField.Equals(value) != true)) {
                    this.CompanyIDField = value;
                    this.RaisePropertyChanged("CompanyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Duty {
            get {
                return this.DutyField;
            }
            set {
                if ((object.ReferenceEquals(this.DutyField, value) != true)) {
                    this.DutyField = value;
                    this.RaisePropertyChanged("Duty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Enabled {
            get {
                return this.EnabledField;
            }
            set {
                if ((this.EnabledField.Equals(value) != true)) {
                    this.EnabledField = value;
                    this.RaisePropertyChanged("Enabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IPAddress {
            get {
                return this.IPAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.IPAddressField, value) != true)) {
                    this.IPAddressField = value;
                    this.RaisePropertyChanged("IPAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuperAdmin {
            get {
                return this.IsSuperAdminField;
            }
            set {
                if ((this.IsSuperAdminField.Equals(value) != true)) {
                    this.IsSuperAdminField = value;
                    this.RaisePropertyChanged("IsSuperAdmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobile {
            get {
                return this.MobileField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileField, value) != true)) {
                    this.MobileField = value;
                    this.RaisePropertyChanged("Mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OICQ {
            get {
                return this.OICQField;
            }
            set {
                if ((object.ReferenceEquals(this.OICQField, value) != true)) {
                    this.OICQField = value;
                    this.RaisePropertyChanged("OICQ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RealName {
            get {
                return this.RealNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RealNameField, value) != true)) {
                    this.RealNameField = value;
                    this.RaisePropertyChanged("RealName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> RoleID {
            get {
                return this.RoleIDField;
            }
            set {
                if ((this.RoleIDField.Equals(value) != true)) {
                    this.RoleIDField = value;
                    this.RaisePropertyChanged("RoleID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sex {
            get {
                return this.SexField;
            }
            set {
                if ((object.ReferenceEquals(this.SexField, value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SystemCode {
            get {
                return this.SystemCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SystemCodeField, value) != true)) {
                    this.SystemCodeField = value;
                    this.RaisePropertyChanged("SystemCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PMSServiceReference.IPMSService")]
    public interface IPMSService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPMSService/UserLogin", ReplyAction="http://tempuri.org/IPMSService/UserLoginResponse")]
        LMS.Services.UserServices.PMSServiceReference.UserLoginResponse UserLogin(LMS.Services.UserServices.PMSServiceReference.UserLoginInfo user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPMSService/GetUser", ReplyAction="http://tempuri.org/IPMSService/GetUserResponse")]
        LMS.Services.UserServices.PMSServiceReference.Response GetUser(LMS.Services.UserServices.PMSServiceReference.UserLoginInfo user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPMSService/AddUser", ReplyAction="http://tempuri.org/IPMSService/AddUserResponse")]
        LMS.Services.UserServices.PMSServiceReference.Response AddUser(LMS.Services.UserServices.PMSServiceReference.UserBaseInfo user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPMSService/ModifyUser", ReplyAction="http://tempuri.org/IPMSService/ModifyUserResponse")]
        LMS.Services.UserServices.PMSServiceReference.Response ModifyUser(LMS.Services.UserServices.PMSServiceReference.UserBaseInfo userInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPMSService/DeleteUser", ReplyAction="http://tempuri.org/IPMSService/DeleteUserResponse")]
        LMS.Services.UserServices.PMSServiceReference.Response DeleteUser(LMS.Services.UserServices.PMSServiceReference.UserLoginInfo user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPMSService/GetUserInfo", ReplyAction="http://tempuri.org/IPMSService/GetUserInfoResponse")]
        LMS.Services.UserServices.PMSServiceReference.UserInfo GetUserInfo(string userName, string systemCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPMSService/GetPermissionsBySystemCode", ReplyAction="http://tempuri.org/IPMSService/GetPermissionsBySystemCodeResponse")]
        LMS.Services.UserServices.PMSServiceReference.PermissionsResponse GetPermissionsBySystemCode(string systemCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPMSServiceChannel : LMS.Services.UserServices.PMSServiceReference.IPMSService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PMSServiceClient : System.ServiceModel.ClientBase<LMS.Services.UserServices.PMSServiceReference.IPMSService>, LMS.Services.UserServices.PMSServiceReference.IPMSService {
        
        public PMSServiceClient() {
        }
        
        public PMSServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PMSServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PMSServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PMSServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LMS.Services.UserServices.PMSServiceReference.UserLoginResponse UserLogin(LMS.Services.UserServices.PMSServiceReference.UserLoginInfo user) {
            return base.Channel.UserLogin(user);
        }
        
        public LMS.Services.UserServices.PMSServiceReference.Response GetUser(LMS.Services.UserServices.PMSServiceReference.UserLoginInfo user) {
            return base.Channel.GetUser(user);
        }
        
        public LMS.Services.UserServices.PMSServiceReference.Response AddUser(LMS.Services.UserServices.PMSServiceReference.UserBaseInfo user) {
            return base.Channel.AddUser(user);
        }
        
        public LMS.Services.UserServices.PMSServiceReference.Response ModifyUser(LMS.Services.UserServices.PMSServiceReference.UserBaseInfo userInfo) {
            return base.Channel.ModifyUser(userInfo);
        }
        
        public LMS.Services.UserServices.PMSServiceReference.Response DeleteUser(LMS.Services.UserServices.PMSServiceReference.UserLoginInfo user) {
            return base.Channel.DeleteUser(user);
        }
        
        public LMS.Services.UserServices.PMSServiceReference.UserInfo GetUserInfo(string userName, string systemCode) {
            return base.Channel.GetUserInfo(userName, systemCode);
        }
        
        public LMS.Services.UserServices.PMSServiceReference.PermissionsResponse GetPermissionsBySystemCode(string systemCode) {
            return base.Channel.GetPermissionsBySystemCode(systemCode);
        }
    }
}
