//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Services.SF.References.Sfexpress {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://appservice.sfexpress.business.ieca.sf.com/", ConfigurationName="References.Sfexpress.SfexpressService")]
    public interface SfexpressService {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string sfexpressService(string xml, string verifyCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SfexpressServiceChannel : LMS.Services.SF.References.Sfexpress.SfexpressService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SfexpressServiceClient : System.ServiceModel.ClientBase<LMS.Services.SF.References.Sfexpress.SfexpressService>, LMS.Services.SF.References.Sfexpress.SfexpressService {
        
        public SfexpressServiceClient() {
        }
        
        public SfexpressServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SfexpressServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SfexpressServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SfexpressServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string sfexpressService(string xml, string verifyCode) {
            return base.Channel.sfexpressService(xml, verifyCode);
        }
    }
}
