//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MQS_Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskQueue
    {
        public long TaskQueueId { get; set; }
        public string QueueName { get; set; }
        public string Value { get; set; }
        public int Status { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
    }
}
