//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Context
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    using LMS.Data.Entity;
    
    
    internal partial class AbnormalWayBillLog_Mapping : EntityTypeConfiguration<AbnormalWayBillLog>
    {
        public AbnormalWayBillLog_Mapping()
        {                        
              this.HasKey(t => t.AbnormalID);        
              this.ToTable("AbnormalWayBillLog");
              this.Property(t => t.AbnormalID).HasColumnName("AbnormalID");
              this.Property(t => t.OperateType).HasColumnName("OperateType");
              this.Property(t => t.AbnormalStatus).HasColumnName("AbnormalStatus");
              this.Property(t => t.AbnormalDescription).HasColumnName("AbnormalDescription").HasMaxLength(1000);
              this.Property(t => t.CreatedBy).HasColumnName("CreatedBy").HasMaxLength(50);
              this.Property(t => t.CreatedOn).HasColumnName("CreatedOn");
              this.Property(t => t.LastUpdatedBy).HasColumnName("LastUpdatedBy").HasMaxLength(50);
              this.Property(t => t.LastUpdatedOn).HasColumnName("LastUpdatedOn");
         }
    }
}
