//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Context
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    using LMS.Data.Entity;
    
    
    internal partial class ApplicationInfo_Mapping : EntityTypeConfiguration<ApplicationInfo>
    {
        public ApplicationInfo_Mapping()
        {                        
              this.HasKey(t => t.ApplicationID);        
              this.ToTable("ApplicationInfos");
              this.Property(t => t.ApplicationID).HasColumnName("ApplicationID");
              this.Property(t => t.CustomerOrderID).HasColumnName("CustomerOrderID");
              this.Property(t => t.WayBillNumber).HasColumnName("WayBillNumber").HasMaxLength(20);
              this.Property(t => t.ApplicationName).HasColumnName("ApplicationName").HasMaxLength(200);
              this.Property(t => t.Qty).HasColumnName("Qty");
              this.Property(t => t.UnitWeight).HasColumnName("UnitWeight");
              this.Property(t => t.UnitPrice).HasColumnName("UnitPrice");
              this.Property(t => t.Total).HasColumnName("Total");
              this.Property(t => t.HSCode).HasColumnName("HSCode").HasMaxLength(50);
              this.Property(t => t.IsDelete).HasColumnName("IsDelete");
              this.Property(t => t.CreatedOn).HasColumnName("CreatedOn");
              this.Property(t => t.CreatedBy).HasColumnName("CreatedBy").HasMaxLength(50);
              this.Property(t => t.LastUpdatedOn).HasColumnName("LastUpdatedOn");
              this.Property(t => t.LastUpdatedBy).HasColumnName("LastUpdatedBy").HasMaxLength(50);
              this.Property(t => t.PickingName).HasColumnName("PickingName").HasMaxLength(500);
              this.Property(t => t.Remark).HasColumnName("Remark").HasMaxLength(500);
              this.Property(t => t.ProductUrl).HasColumnName("ProductUrl").HasMaxLength(500);
              this.HasOptional(t => t.CustomerOrderInfo).WithMany(t => t.ApplicationInfos).HasForeignKey(d => d.CustomerOrderID);
              this.HasOptional(t => t.WayBillInfo).WithMany(t => t.ApplicationInfos).HasForeignKey(d => d.WayBillNumber);
         }
    }
}
