//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Context
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    using LMS.Data.Entity;
    
    
    internal partial class B2CPreAlertLogs_Mapping : EntityTypeConfiguration<B2CPreAlertLogs>
    {
        public B2CPreAlertLogs_Mapping()
        {                        
              this.HasKey(t => t.WayBillNumber);        
              this.ToTable("B2CPreAlertLogs");
              this.Property(t => t.WayBillNumber).HasColumnName("WayBillNumber").IsRequired().HasMaxLength(20);
              this.Property(t => t.ShippingMethod).HasColumnName("ShippingMethod").HasMaxLength(10);
              this.Property(t => t.PreAlertID).HasColumnName("PreAlertID");
              this.Property(t => t.ErrorMsg).HasColumnName("ErrorMsg").HasMaxLength(200);
              this.Property(t => t.ErrorCode).HasColumnName("ErrorCode");
              this.Property(t => t.ErrorDetails).HasColumnName("ErrorDetails").HasMaxLength(2000);
              this.Property(t => t.Status).HasColumnName("Status");
              this.Property(t => t.CreatedOn).HasColumnName("CreatedOn");
              this.Property(t => t.CreatedBy).HasColumnName("CreatedBy").HasMaxLength(50);
              this.Property(t => t.LastUpdatedOn).HasColumnName("LastUpdatedOn");
              this.Property(t => t.LastUpdatedBy).HasColumnName("LastUpdatedBy").HasMaxLength(50);
              this.Property(t => t.PreAlertBatchNo).HasColumnName("PreAlertBatchNo").HasMaxLength(20);
         }
    }
}
