//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Context
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    using LMS.Data.Entity;
    
    
    internal partial class Category_Mapping : EntityTypeConfiguration<Category>
    {
        public Category_Mapping()
        {                        
              this.HasKey(t => t.CategoryID);        
              this.ToTable("Category");
              this.Property(t => t.CategoryID).HasColumnName("CategoryID").HasDatabaseGeneratedOption(new Nullable<DatabaseGeneratedOption>(DatabaseGeneratedOption.None));
              this.Property(t => t.Name).HasColumnName("Name").IsRequired().HasMaxLength(50);
              this.Property(t => t.EnglishName).HasColumnName("EnglishName").HasMaxLength(50);
              this.Property(t => t.ParentID).HasColumnName("ParentID");
              this.Property(t => t.ParentPath).HasColumnName("ParentPath").IsRequired();
              this.Property(t => t.Level).HasColumnName("Level");
              this.Property(t => t.Sort).HasColumnName("Sort");
              this.Property(t => t.Pic).HasColumnName("Pic").HasMaxLength(500);
              this.Property(t => t.Description).HasColumnName("Description");
              this.Property(t => t.SeoTitle).HasColumnName("SeoTitle");
              this.Property(t => t.SeoKeywords).HasColumnName("SeoKeywords");
              this.Property(t => t.SeoDescription).HasColumnName("SeoDescription");
              this.Property(t => t.Status).HasColumnName("Status");
              this.Property(t => t.CreatedBy).HasColumnName("CreatedBy").HasMaxLength(50);
              this.Property(t => t.CreatedOn).HasColumnName("CreatedOn");
              this.Property(t => t.LastUpdatedBy).HasColumnName("LastUpdatedBy").HasMaxLength(50);
              this.Property(t => t.LastUpdatedOn).HasColumnName("LastUpdatedOn");
         }
    }
}
