//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Context
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    using LMS.Data.Entity;
    
    
    internal partial class Country_Mapping : EntityTypeConfiguration<Country>
    {
        public Country_Mapping()
        {                        
              this.HasKey(t => t.CountryCode);        
              this.ToTable("Countries");
              this.Property(t => t.CountryCode).HasColumnName("CountryCode").IsRequired().HasMaxLength(5);
              this.Property(t => t.Name).HasColumnName("Name").IsRequired().HasMaxLength(100);
              this.Property(t => t.AllowsShipping).HasColumnName("AllowsShipping");
              this.Property(t => t.ThreeLetterISOCode).HasColumnName("ThreeLetterISOCode").IsRequired().HasMaxLength(3);
              this.Property(t => t.NumericISOCode).HasColumnName("NumericISOCode");
              this.Property(t => t.Status).HasColumnName("Status");
              this.Property(t => t.DisplayOrder).HasColumnName("DisplayOrder");
              this.Property(t => t.ChineseName).HasColumnName("ChineseName").IsRequired().HasMaxLength(100);
         }
    }
}
