//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Context
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    using LMS.Data.Entity;
    
    
    internal partial class CustomerUpdatedLog_Mapping : EntityTypeConfiguration<CustomerUpdatedLog>
    {
        public CustomerUpdatedLog_Mapping()
        {                        
              this.HasKey(t => t.ID);        
              this.ToTable("CustomerUpdatedLogs");
              this.Property(t => t.CustomerID).HasColumnName("CustomerID");
              this.Property(t => t.CustomerCode).HasColumnName("CustomerCode").HasMaxLength(20);
              this.Property(t => t.PaymentTypeID).HasColumnName("PaymentTypeID");
              this.Property(t => t.EnableCredit).HasColumnName("EnableCredit");
              this.Property(t => t.MaxDelinquentAmounts).HasColumnName("MaxDelinquentAmounts");
              this.Property(t => t.ChangedBy).HasColumnName("ChangedBy").HasMaxLength(50);
              this.Property(t => t.UpdatedOn).HasColumnName("UpdatedOn");
              this.Property(t => t.ID).HasColumnName("ID");
         }
    }
}
