//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Context
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    using LMS.Data.Entity;
    
    
    internal partial class CustomerManagerInfo_Mapping : EntityTypeConfiguration<CustomerManagerInfo>
    {
        public CustomerManagerInfo_Mapping()
        {                        
              this.HasKey(t => t.ID);        
              this.ToTable("CustomerManagerInfos");
              this.Property(t => t.ID).HasColumnName("ID");
              this.Property(t => t.Name).HasColumnName("Name").HasMaxLength(50);
              this.Property(t => t.EnName).HasColumnName("EnName").HasMaxLength(50);
              this.Property(t => t.DepartmentName).HasColumnName("DepartmentName").HasMaxLength(50);
              this.Property(t => t.Sex).HasColumnName("Sex");
              this.Property(t => t.Tel).HasColumnName("Tel").HasMaxLength(30);
              this.Property(t => t.Mobile).HasColumnName("Mobile").HasMaxLength(30);
              this.Property(t => t.EMail).HasColumnName("EMail").HasMaxLength(50);
              this.Property(t => t.Status).HasColumnName("Status");
              this.Property(t => t.CreatedOn).HasColumnName("CreatedOn");
              this.Property(t => t.CreatedBy).HasColumnName("CreatedBy").HasMaxLength(50);
              this.Property(t => t.LastUpdatedOn).HasColumnName("LastUpdatedOn");
              this.Property(t => t.LastUpdatedBy).HasColumnName("LastUpdatedBy").HasMaxLength(50);
         }
    }
}
