//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Context
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    using LMS.Data.Entity;
    
    
    internal partial class CustomerOrderStatus_Mapping : EntityTypeConfiguration<CustomerOrderStatus>
    {
        public CustomerOrderStatus_Mapping()
        {                        
              this.HasKey(t => t.ID);        
              this.ToTable("CustomerOrderStatuses");
              this.Property(t => t.ID).HasColumnName("ID");
              this.Property(t => t.CustomerOrderID).HasColumnName("CustomerOrderID");
              this.Property(t => t.CreatedOn).HasColumnName("CreatedOn");
              this.Property(t => t.Status).HasColumnName("Status");
              this.Property(t => t.Remark).HasColumnName("Remark").HasMaxLength(500);
              this.HasRequired(t => t.CustomerOrderInfo).WithMany(t => t.CustomerOrderStatuses).HasForeignKey(d => d.CustomerOrderID);
         }
    }
}
