//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Context
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    using LMS.Data.Entity;
    
    
    internal partial class Customer_Mapping : EntityTypeConfiguration<Customer>
    {
        public Customer_Mapping()
        {                        
              this.HasKey(t => t.CustomerID);        
              this.ToTable("Customers");
              this.Property(t => t.CustomerID).HasColumnName("CustomerID");
              this.Property(t => t.CustomerCode).HasColumnName("CustomerCode").IsRequired().HasMaxLength(20);
              this.Property(t => t.AccountID).HasColumnName("AccountID").IsRequired().HasMaxLength(100);
              this.Property(t => t.AccountPassWord).HasColumnName("AccountPassWord").IsRequired().HasMaxLength(128);
              this.Property(t => t.CustomerTypeID).HasColumnName("CustomerTypeID");
              this.Property(t => t.Name).HasColumnName("Name").IsRequired().HasMaxLength(128);
              this.Property(t => t.EnName).HasColumnName("EnName").HasMaxLength(128);
              this.Property(t => t.LinkMan).HasColumnName("LinkMan").HasMaxLength(50);
              this.Property(t => t.WebSite).HasColumnName("WebSite").HasMaxLength(200);
              this.Property(t => t.PaymentTypeID).HasColumnName("PaymentTypeID");
              this.Property(t => t.Address).HasColumnName("Address").HasMaxLength(128);
              this.Property(t => t.EnAddress).HasColumnName("EnAddress").HasMaxLength(128);
              this.Property(t => t.Country).HasColumnName("Country").HasMaxLength(64);
              this.Property(t => t.City).HasColumnName("City").HasMaxLength(64);
              this.Property(t => t.Province).HasColumnName("Province").HasMaxLength(64);
              this.Property(t => t.Tele).HasColumnName("Tele").HasMaxLength(64);
              this.Property(t => t.Mobile).HasColumnName("Mobile").HasMaxLength(64);
              this.Property(t => t.Email).HasColumnName("Email").HasMaxLength(64);
              this.Property(t => t.Fax).HasColumnName("Fax").HasMaxLength(64);
              this.Property(t => t.PostCode).HasColumnName("PostCode").HasMaxLength(64);
              this.Property(t => t.QQ).HasColumnName("QQ").HasMaxLength(64);
              this.Property(t => t.MSN).HasColumnName("MSN").HasMaxLength(64);
              this.Property(t => t.Skype).HasColumnName("Skype").HasMaxLength(64);
              this.Property(t => t.Status).HasColumnName("Status");
              this.Property(t => t.LastLoginIP).HasColumnName("LastLoginIP").HasMaxLength(50);
              this.Property(t => t.LoginCount).HasColumnName("LoginCount");
              this.Property(t => t.EnableCredit).HasColumnName("EnableCredit");
              this.Property(t => t.MaxDelinquentAmounts).HasColumnName("MaxDelinquentAmounts");
              this.Property(t => t.Remark).HasColumnName("Remark").HasMaxLength(512);
              this.Property(t => t.CreatedOn).HasColumnName("CreatedOn");
              this.Property(t => t.CreatedBy).HasColumnName("CreatedBy").HasMaxLength(50);
              this.Property(t => t.LastUpdatedOn).HasColumnName("LastUpdatedOn");
              this.Property(t => t.LastUpdatedBy).HasColumnName("LastUpdatedBy").HasMaxLength(50);
              this.Property(t => t.ApiKey).HasColumnName("ApiKey").HasMaxLength(200);
              this.Property(t => t.ApiSecret).HasColumnName("ApiSecret").HasMaxLength(200);
              this.Property(t => t.CustomerManager).HasColumnName("CustomerManager").HasMaxLength(50);
              this.HasOptional(t => t.PaymentType).WithMany(t => t.Customers).HasForeignKey(d => d.PaymentTypeID);
         }
    }
}
