//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Context
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    using LMS.Data.Entity;
    
    
    internal partial class CustomerAmountRecord_Mapping : EntityTypeConfiguration<CustomerAmountRecord>
    {
        public CustomerAmountRecord_Mapping()
        {                        
              this.HasKey(t => t.SerialNumber);        
              this.ToTable("CustomerAmountRecords");
              this.Property(t => t.SerialNumber).HasColumnName("SerialNumber").IsRequired().HasMaxLength(16);
              this.Property(t => t.WayBillNumber).HasColumnName("WayBillNumber").HasMaxLength(20);
              this.Property(t => t.TransactionNo).HasColumnName("TransactionNo").HasMaxLength(50);
              this.Property(t => t.MoneyChangeTypeID).HasColumnName("MoneyChangeTypeID");
              this.Property(t => t.FeeTypeID).HasColumnName("FeeTypeID");
              this.Property(t => t.Amount).HasColumnName("Amount");
              this.Property(t => t.Balance).HasColumnName("Balance");
              this.Property(t => t.CreatedOn).HasColumnName("CreatedOn");
              this.Property(t => t.CreatedBy).HasColumnName("CreatedBy").HasMaxLength(50);
              this.Property(t => t.Remark).HasColumnName("Remark").HasMaxLength(500);
              this.Property(t => t.CustomerID).HasColumnName("CustomerID");
              this.Property(t => t.CustomerCode).HasColumnName("CustomerCode").HasMaxLength(20);
              this.HasOptional(t => t.Customer).WithMany(t => t.CustomerAmountRecords).HasForeignKey(d => d.CustomerID);
              this.HasOptional(t => t.FeeType).WithMany(t => t.CustomerAmountRecords).HasForeignKey(d => d.FeeTypeID);
              this.HasOptional(t => t.MoneyChangeTypeInfo).WithMany(t => t.CustomerAmountRecords).HasForeignKey(d => d.MoneyChangeTypeID);
         }
    }
}
