//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Context
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    using LMS.Data.Entity;
    
    
    internal partial class CustomerBalance_Mapping : EntityTypeConfiguration<CustomerBalance>
    {
        public CustomerBalance_Mapping()
        {                        
              this.HasKey(t => t.CustomerID);        
              this.ToTable("CustomerBalances");
              this.Property(t => t.CustomerID).HasColumnName("CustomerID");
              this.Property(t => t.CustomerCode).HasColumnName("CustomerCode").HasMaxLength(20);
              this.Property(t => t.Balance).HasColumnName("Balance");
              this.Property(t => t.CreatedOn).HasColumnName("CreatedOn");
              this.Property(t => t.LastUpdatedOn).HasColumnName("LastUpdatedOn");
              this.HasRequired(t => t.Customer).WithOptional(t => t.CustomerBalance);
         }
    }
}
