//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Context
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    using LMS.Data.Entity;
    
    
    internal partial class DeliveryDeviation_Mapping : EntityTypeConfiguration<DeliveryDeviation>
    {
        public DeliveryDeviation_Mapping()
        {                        
              this.HasKey(t => t.DeviationID);        
              this.ToTable("DeliveryDeviations");
              this.Property(t => t.DeviationID).HasColumnName("DeviationID");
              this.Property(t => t.VenderName).HasColumnName("VenderName").HasMaxLength(200);
              this.Property(t => t.VenderCode).HasColumnName("VenderCode").HasMaxLength(50);
              this.Property(t => t.VenderId).HasColumnName("VenderId");
              this.Property(t => t.ShippingmethodID).HasColumnName("ShippingmethodID");
              this.Property(t => t.ShippingmethodName).HasColumnName("ShippingmethodName").HasMaxLength(100);
              this.Property(t => t.DeviationType).HasColumnName("DeviationType");
              this.Property(t => t.DeviationValue).HasColumnName("DeviationValue");
              this.Property(t => t.DeviationRate).HasColumnName("DeviationRate");
              this.Property(t => t.CreatedOn).HasColumnName("CreatedOn");
              this.Property(t => t.CreatedBy).HasColumnName("CreatedBy").HasMaxLength(50);
              this.Property(t => t.LastUpdatedOn).HasColumnName("LastUpdatedOn");
              this.Property(t => t.LastUpdatedBy).HasColumnName("LastUpdatedBy").HasMaxLength(50);
         }
    }
}
