//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Context
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    using LMS.Data.Entity;
    
    
    internal partial class DeliveryImportAccountChecksTemp_Mapping : EntityTypeConfiguration<DeliveryImportAccountChecksTemp>
    {
        public DeliveryImportAccountChecksTemp_Mapping()
        {                        
              this.HasKey(t => t.ID);        
              this.ToTable("DeliveryImportAccountChecksTemp");
              this.Property(t => t.ID).HasColumnName("ID");
              this.Property(t => t.OrderNumber).HasColumnName("OrderNumber").HasMaxLength(50);
              this.Property(t => t.WayBillNumber).HasColumnName("WayBillNumber").HasMaxLength(20);
              this.Property(t => t.ReceivingDate).HasColumnName("ReceivingDate");
              this.Property(t => t.VenderName).HasColumnName("VenderName").HasMaxLength(50);
              this.Property(t => t.ShippingMethodName).HasColumnName("ShippingMethodName").HasMaxLength(100);
              this.Property(t => t.CountryName).HasColumnName("CountryName").HasMaxLength(50);
              this.Property(t => t.Weight).HasColumnName("Weight");
              this.Property(t => t.SettleWeight).HasColumnName("SettleWeight");
              this.Property(t => t.TotalFee).HasColumnName("TotalFee");
              this.Property(t => t.CreatedBy).HasColumnName("CreatedBy").HasMaxLength(50);
              this.Property(t => t.OriginalSettleWeight).HasColumnName("OriginalSettleWeight");
              this.Property(t => t.OriginalTotalFee).HasColumnName("OriginalTotalFee");
              this.Property(t => t.WeightDeviation).HasColumnName("WeightDeviation");
              this.Property(t => t.FeeDeviation).HasColumnName("FeeDeviation");
         }
    }
}
