//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Context
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    using LMS.Data.Entity;
    
    
    internal partial class DeliveryImportAccountCheck_Mapping : EntityTypeConfiguration<DeliveryImportAccountCheck>
    {
        public DeliveryImportAccountCheck_Mapping()
        {                        
              this.HasKey(t => t.DeliveryImportAccountCheckID);        
              this.ToTable("DeliveryImportAccountChecks");
              this.Property(t => t.DeliveryImportAccountCheckID).HasColumnName("DeliveryImportAccountCheckID");
              this.Property(t => t.WayBillNumber).HasColumnName("WayBillNumber").HasMaxLength(50);
              this.Property(t => t.OrderNumber).HasColumnName("OrderNumber").HasMaxLength(50);
              this.Property(t => t.ReceivingDate).HasColumnName("ReceivingDate");
              this.Property(t => t.VenderName).HasColumnName("VenderName").HasMaxLength(50);
              this.Property(t => t.ShippingMethodName).HasColumnName("ShippingMethodName").HasMaxLength(100);
              this.Property(t => t.CountryName).HasColumnName("CountryName").HasMaxLength(50);
              this.Property(t => t.Weight).HasColumnName("Weight");
              this.Property(t => t.SettleWeight).HasColumnName("SettleWeight");
              this.Property(t => t.TotalFee).HasColumnName("TotalFee");
              this.Property(t => t.CreatedOn).HasColumnName("CreatedOn");
              this.Property(t => t.CreatedBy).HasColumnName("CreatedBy").HasMaxLength(50);
              this.Property(t => t.Status).HasColumnName("Status");
              this.Property(t => t.UserName).HasColumnName("UserName").HasMaxLength(50);
         }
    }
}
