//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Context
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    using LMS.Data.Entity;
    
    
    internal partial class DeliveryChannelConfiguration_Mapping : EntityTypeConfiguration<DeliveryChannelConfiguration>
    {
        public DeliveryChannelConfiguration_Mapping()
        {                        
              this.HasKey(t => t.DeliveryChannelConfigurationId);        
              this.ToTable("DeliveryChannelConfigurations");
              this.Property(t => t.DeliveryChannelConfigurationId).HasColumnName("DeliveryChannelConfigurationId");
              this.Property(t => t.InShippingMethodId).HasColumnName("InShippingMethodId");
              this.Property(t => t.InShippingMethodName).HasColumnName("InShippingMethodName").IsRequired().HasMaxLength(100);
              this.Property(t => t.VenderId).HasColumnName("VenderId");
              this.Property(t => t.VenderName).HasColumnName("VenderName").IsRequired().HasMaxLength(100);
              this.Property(t => t.OutShippingMethodId).HasColumnName("OutShippingMethodId");
              this.Property(t => t.OutShippingMethodName).HasColumnName("OutShippingMethodName").IsRequired().HasMaxLength(100);
              this.Property(t => t.CreatedOn).HasColumnName("CreatedOn");
              this.Property(t => t.CreatedBy).HasColumnName("CreatedBy").IsRequired().HasMaxLength(50);
         }
    }
}
