//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Context
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    using LMS.Data.Entity;
    
    
    internal partial class DeliveryFee_Mapping : EntityTypeConfiguration<DeliveryFee>
    {
        public DeliveryFee_Mapping()
        {                        
              this.HasKey(t => t.DeliveryFeeID);        
              this.ToTable("DeliveryFees");
              this.Property(t => t.DeliveryFeeID).HasColumnName("DeliveryFeeID");
              this.Property(t => t.WayBillNumber).HasColumnName("WayBillNumber").IsRequired().HasMaxLength(20);
              this.Property(t => t.CustomerOrderNumber).HasColumnName("CustomerOrderNumber").HasMaxLength(50);
              this.Property(t => t.Trackingnumber).HasColumnName("Trackingnumber").HasMaxLength(50);
              this.Property(t => t.VenderName).HasColumnName("VenderName").HasMaxLength(200);
              this.Property(t => t.VenderCode).HasColumnName("VenderCode").HasMaxLength(50);
              this.Property(t => t.VenderId).HasColumnName("VenderId");
              this.Property(t => t.ShippingmethodID).HasColumnName("ShippingmethodID");
              this.Property(t => t.ShippingmethodName).HasColumnName("ShippingmethodName").HasMaxLength(100);
              this.Property(t => t.SetWeight).HasColumnName("SetWeight");
              this.Property(t => t.AprroveWeight).HasColumnName("AprroveWeight");
              this.Property(t => t.Status).HasColumnName("Status");
              this.Property(t => t.Remark).HasColumnName("Remark").HasMaxLength(4000);
              this.Property(t => t.Auditor).HasColumnName("Auditor").HasMaxLength(50);
              this.Property(t => t.AuditorDate).HasColumnName("AuditorDate");
              this.Property(t => t.CreatedOn).HasColumnName("CreatedOn");
              this.Property(t => t.CreatedBy).HasColumnName("CreatedBy").HasMaxLength(50);
              this.Property(t => t.LastUpdatedOn).HasColumnName("LastUpdatedOn");
              this.Property(t => t.LastUpdatedBy).HasColumnName("LastUpdatedBy").HasMaxLength(50);
              this.Property(t => t.IsNoGet).HasColumnName("IsNoGet");
              this.HasRequired(t => t.WayBillInfo).WithMany(t => t.DeliveryFees).HasForeignKey(d => d.WayBillNumber);
         }
    }
}
