//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Context
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    using LMS.Data.Entity;
    
    
    internal partial class DictionaryType_Mapping : EntityTypeConfiguration<DictionaryType>
    {
        public DictionaryType_Mapping()
        {                        
              this.HasKey(t => t.DicTypeId);        
              this.ToTable("DictionaryTypes");
              this.Property(t => t.DicTypeId).HasColumnName("DicTypeId").IsRequired().HasMaxLength(50);
              this.Property(t => t.Name).HasColumnName("Name").HasMaxLength(50);
              this.Property(t => t.EnglishName).HasColumnName("EnglishName").HasMaxLength(50);
              this.Property(t => t.ParentId).HasColumnName("ParentId").IsRequired().HasMaxLength(50);
              this.Property(t => t.SpecialName).HasColumnName("SpecialName").HasMaxLength(50);
              this.Property(t => t.Remark).HasColumnName("Remark").HasMaxLength(200);
              this.Property(t => t.Sort).HasColumnName("Sort");
              this.Property(t => t.IsParent).HasColumnName("IsParent");
              this.Property(t => t.IsEnable).HasColumnName("IsEnable");
              this.Property(t => t.IsDelete).HasColumnName("IsDelete");
              this.Property(t => t.CreatedOn).HasColumnName("CreatedOn");
              this.Property(t => t.CreatedBy).HasColumnName("CreatedBy").HasMaxLength(50);
              this.Property(t => t.LastUpdatedOn).HasColumnName("LastUpdatedOn");
              this.Property(t => t.LastUpdatedBy).HasColumnName("LastUpdatedBy").HasMaxLength(50);
         }
    }
}
