//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Context
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    using LMS.Data.Entity;
    
    
    internal partial class EubAccountInfo_Mapping : EntityTypeConfiguration<EubAccountInfo>
    {
        public EubAccountInfo_Mapping()
        {                        
              this.HasKey(t => t.EubAccountId);        
              this.ToTable("EubAccountInfos");
              this.Property(t => t.EubAccountId).HasColumnName("EubAccountId");
              this.Property(t => t.Account).HasColumnName("Account").IsRequired().HasMaxLength(50);
              this.Property(t => t.ShippingMethodId).HasColumnName("ShippingMethodId");
              this.Property(t => t.AuthorizationCode).HasColumnName("AuthorizationCode").HasMaxLength(200);
              this.Property(t => t.CountryCode).HasColumnName("CountryCode").HasMaxLength(5);
              this.Property(t => t.State).HasColumnName("State").HasMaxLength(50);
              this.Property(t => t.City).HasColumnName("City").HasMaxLength(50);
              this.Property(t => t.ZipCode).HasColumnName("ZipCode").HasMaxLength(20);
              this.Property(t => t.Phone).HasColumnName("Phone").HasMaxLength(50);
              this.Property(t => t.CompanyName).HasColumnName("CompanyName").HasMaxLength(200);
              this.Property(t => t.Address).HasColumnName("Address").HasMaxLength(200);
              this.Property(t => t.Email).HasColumnName("Email").HasMaxLength(200);
              this.Property(t => t.Status).HasColumnName("Status");
              this.Property(t => t.CreatedOn).HasColumnName("CreatedOn");
              this.Property(t => t.CreatedBy).HasColumnName("CreatedBy").HasMaxLength(50);
              this.Property(t => t.LastUpdatedOn).HasColumnName("LastUpdatedOn");
              this.Property(t => t.LastUpdatedBy).HasColumnName("LastUpdatedBy").HasMaxLength(50);
              this.Property(t => t.ServerUrl).HasColumnName("ServerUrl").HasMaxLength(200);
              this.Property(t => t.Name).HasColumnName("Name").IsRequired().HasMaxLength(100);
              this.Property(t => t.Mobile).HasColumnName("Mobile").HasMaxLength(50);
              this.Property(t => t.County).HasColumnName("County").HasMaxLength(50);
         }
    }
}
