//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Context
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    using LMS.Data.Entity;
    
    
    internal partial class EubWayBillApplicationInfo_Mapping : EntityTypeConfiguration<EubWayBillApplicationInfo>
    {
        public EubWayBillApplicationInfo_Mapping()
        {                        
              this.HasKey(t => t.EubOrderId);        
              this.ToTable("EubWayBillApplicationInfos");
              this.Property(t => t.EubOrderId).HasColumnName("EubOrderId");
              this.Property(t => t.WayBillNumber).HasColumnName("WayBillNumber").IsRequired().HasMaxLength(20);
              this.Property(t => t.ShippingMethodID).HasColumnName("ShippingMethodID");
              this.Property(t => t.BatchNumber).HasColumnName("BatchNumber").IsRequired().HasMaxLength(30);
              this.Property(t => t.PrintFormat).HasColumnName("PrintFormat");
              this.Property(t => t.LocalDownLoad).HasColumnName("LocalDownLoad").HasMaxLength(200);
              this.Property(t => t.EubDownLoad).HasColumnName("EubDownLoad").HasMaxLength(200);
              this.Property(t => t.Status).HasColumnName("Status");
              this.Property(t => t.CreatedOn).HasColumnName("CreatedOn");
              this.Property(t => t.CreatedBy).HasColumnName("CreatedBy").HasMaxLength(50);
              this.Property(t => t.LastUpdatedOn).HasColumnName("LastUpdatedOn");
              this.Property(t => t.LastUpdatedBy).HasColumnName("LastUpdatedBy").HasMaxLength(50);
              this.HasRequired(t => t.WayBillInfo).WithMany(t => t.EubWayBillApplicationInfos).HasForeignKey(d => d.WayBillNumber);
         }
    }
}
