//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Context
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    using LMS.Data.Entity;
    
    
    internal partial class ExpressAccountInfo_Mapping : EntityTypeConfiguration<ExpressAccountInfo>
    {
        public ExpressAccountInfo_Mapping()
        {                        
              this.HasKey(t => t.Id);        
              this.ToTable("ExpressAccountInfos");
              this.Property(t => t.Id).HasColumnName("Id");
              this.Property(t => t.Account).HasColumnName("Account").HasMaxLength(100);
              this.Property(t => t.Password).HasColumnName("Password").HasMaxLength(100);
              this.Property(t => t.ShipperAccountNumber).HasColumnName("ShipperAccountNumber").HasMaxLength(50);
              this.Property(t => t.ServerUrl).HasColumnName("ServerUrl").HasMaxLength(200);
              this.Property(t => t.CompanyName).HasColumnName("CompanyName").HasMaxLength(100);
              this.Property(t => t.Address).HasColumnName("Address").HasMaxLength(200);
              this.Property(t => t.City).HasColumnName("City").HasMaxLength(50);
              this.Property(t => t.CountryCode).HasColumnName("CountryCode").HasMaxLength(50);
              this.Property(t => t.CountryName).HasColumnName("CountryName").HasMaxLength(50);
              this.Property(t => t.PostalCode).HasColumnName("PostalCode").HasMaxLength(50);
              this.Property(t => t.DivisionCode).HasColumnName("DivisionCode").HasMaxLength(50);
              this.Property(t => t.PersonName).HasColumnName("PersonName").HasMaxLength(50);
              this.Property(t => t.PhoneNumber).HasColumnName("PhoneNumber").HasMaxLength(50);
              this.Property(t => t.PhoneExtension).HasColumnName("PhoneExtension").HasMaxLength(50);
              this.Property(t => t.Telex).HasColumnName("Telex").HasMaxLength(50);
              this.Property(t => t.FaxNumber).HasColumnName("FaxNumber").HasMaxLength(50);
              this.Property(t => t.Origin).HasColumnName("Origin").HasMaxLength(50);
              this.Property(t => t.ShippingTaxId).HasColumnName("ShippingTaxId").HasMaxLength(50);
              this.Property(t => t.ShippingMethodId).HasColumnName("ShippingMethodId");
              this.Property(t => t.VenderCode).HasColumnName("VenderCode").HasMaxLength(50);
              this.Property(t => t.CreatedOn).HasColumnName("CreatedOn");
              this.Property(t => t.CreatedBy).HasColumnName("CreatedBy").HasMaxLength(50);
              this.Property(t => t.LastUpdatedOn).HasColumnName("LastUpdatedOn");
              this.Property(t => t.LastUpdatedBy).HasColumnName("LastUpdatedBy").HasMaxLength(50);
         }
    }
}
