//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Context
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    using LMS.Data.Entity;
    
    
    internal partial class FuzhouPostLog_Mapping : EntityTypeConfiguration<FuzhouPostLog>
    {
        public FuzhouPostLog_Mapping()
        {                        
              this.HasKey(t => t.ID);        
              this.ToTable("FuzhouPostLogs");
              this.Property(t => t.ID).HasColumnName("ID");
              this.Property(t => t.WayBillNumber).HasColumnName("WayBillNumber").IsRequired().HasMaxLength(20);
              this.Property(t => t.Status).HasColumnName("Status");
              this.Property(t => t.OutShippingMethodID).HasColumnName("OutShippingMethodID");
              this.Property(t => t.ErrorNumber).HasColumnName("ErrorNumber").HasMaxLength(1000);
              this.Property(t => t.CreateOn).HasColumnName("CreateOn");
              this.Property(t => t.LastUpdateOn).HasColumnName("LastUpdateOn");
         }
    }
}
