//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Context
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    using LMS.Data.Entity;
    
    
    internal partial class GZPacketAddressInfo_Mapping : EntityTypeConfiguration<GZPacketAddressInfo>
    {
        public GZPacketAddressInfo_Mapping()
        {                        
              this.HasKey(t => t.ID);        
              this.ToTable("GZPacketAddressInfos");
              this.Property(t => t.ID).HasColumnName("ID");
              this.Property(t => t.Name).HasColumnName("Name").HasMaxLength(50);
              this.Property(t => t.Address).HasColumnName("Address").HasMaxLength(50);
              this.Property(t => t.Number).HasColumnName("Number");
              this.Property(t => t.Status).HasColumnName("Status");
         }
    }
}
