//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Context
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    using LMS.Data.Entity;
    
    
    internal partial class InStorageOrSettlementRelational_Mapping : EntityTypeConfiguration<InStorageOrSettlementRelational>
    {
        public InStorageOrSettlementRelational_Mapping()
        {                        
              this.HasKey(t => t.ID);        
              this.ToTable("InStorageOrSettlementRelationals");
              this.Property(t => t.ID).HasColumnName("ID");
              this.Property(t => t.SettlementNumber).HasColumnName("SettlementNumber").HasMaxLength(20);
              this.Property(t => t.InStorageID).HasColumnName("InStorageID").HasMaxLength(16);
              this.HasOptional(t => t.InStorageInfo).WithMany(t => t.InStorageOrSettlementRelationals).HasForeignKey(d => d.InStorageID);
              this.HasOptional(t => t.SettlementInfo).WithMany(t => t.InStorageOrSettlementRelationals).HasForeignKey(d => d.SettlementNumber);
         }
    }
}
