//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Context
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    using LMS.Data.Entity;
    
    
    internal partial class InStorageInfo_Mapping : EntityTypeConfiguration<InStorageInfo>
    {
        public InStorageInfo_Mapping()
        {                        
              this.HasKey(t => t.InStorageID);        
              this.ToTable("InStorageInfos");
              this.Property(t => t.InStorageID).HasColumnName("InStorageID").IsRequired().HasMaxLength(16);
              this.Property(t => t.ReceivingClerk).HasColumnName("ReceivingClerk").HasMaxLength(50);
              this.Property(t => t.CustomerCode).HasColumnName("CustomerCode").HasMaxLength(20);
              this.Property(t => t.TotalWeight).HasColumnName("TotalWeight");
              this.Property(t => t.TotalQty).HasColumnName("TotalQty");
              this.Property(t => t.MaterialsFee).HasColumnName("MaterialsFee");
              this.Property(t => t.TotalFee).HasColumnName("TotalFee");
              this.Property(t => t.Freight).HasColumnName("Freight");
              this.Property(t => t.Register).HasColumnName("Register");
              this.Property(t => t.FuelCharge).HasColumnName("FuelCharge");
              this.Property(t => t.Surcharge).HasColumnName("Surcharge");
              this.Property(t => t.Status).HasColumnName("Status");
              this.Property(t => t.CreatedOn).HasColumnName("CreatedOn");
              this.Property(t => t.CreatedBy).HasColumnName("CreatedBy").HasMaxLength(50);
              this.Property(t => t.LastUpdatedOn).HasColumnName("LastUpdatedOn");
              this.Property(t => t.LastUpdatedBy).HasColumnName("LastUpdatedBy").HasMaxLength(50);
              this.Property(t => t.Remark).HasColumnName("Remark").HasMaxLength(300);
              this.Property(t => t.TariffPrepayFee).HasColumnName("TariffPrepayFee");
              this.Property(t => t.PhysicalTotalWeight).HasColumnName("PhysicalTotalWeight");
              this.Property(t => t.PaymentTypeID).HasColumnName("PaymentTypeID");
         }
    }
}
