//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Context
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    using LMS.Data.Entity;
    
    
    internal partial class LithuaniaInfo_Mapping : EntityTypeConfiguration<LithuaniaInfo>
    {
        public LithuaniaInfo_Mapping()
        {                        
              this.HasKey(t => t.WayBillNumber);        
              this.ToTable("LithuaniaInfos");
              this.Property(t => t.WayBillNumber).HasColumnName("WayBillNumber").IsRequired().HasMaxLength(20);
              this.Property(t => t.MailNo).HasColumnName("MailNo").HasMaxLength(50);
              this.Property(t => t.OriginCode).HasColumnName("OriginCode").HasMaxLength(5);
              this.Property(t => t.DestCode).HasColumnName("DestCode").HasMaxLength(5);
              this.Property(t => t.FilterResult).HasColumnName("FilterResult").HasMaxLength(5);
              this.Property(t => t.AgentMailNo).HasColumnName("AgentMailNo").HasMaxLength(50);
              this.Property(t => t.TrackNumber).HasColumnName("TrackNumber").HasMaxLength(30);
              this.Property(t => t.Remark).HasColumnName("Remark").HasMaxLength(100);
              this.Property(t => t.Status).HasColumnName("Status");
              this.Property(t => t.CreatedOn).HasColumnName("CreatedOn");
              this.Property(t => t.CreatedBy).HasColumnName("CreatedBy").HasMaxLength(50);
              this.Property(t => t.LastUpdatedOn).HasColumnName("LastUpdatedOn");
              this.Property(t => t.LastUpdatedBy).HasColumnName("LastUpdatedBy").HasMaxLength(50);
         }
    }
}
