//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Context
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    using LMS.Data.Entity;
    
    
    internal partial class MailExchangeBagLog_Mapping : EntityTypeConfiguration<MailExchangeBagLog>
    {
        public MailExchangeBagLog_Mapping()
        {                        
              this.HasKey(t => t.ID);        
              this.ToTable("MailExchangeBagLogs");
              this.Property(t => t.ID).HasColumnName("ID");
              this.Property(t => t.TrackNumber).HasColumnName("TrackNumber").IsRequired().HasMaxLength(20);
              this.Property(t => t.PostBagNumber).HasColumnName("PostBagNumber").IsRequired().HasMaxLength(20);
              this.Property(t => t.NewPostBagNumber).HasColumnName("NewPostBagNumber").IsRequired().HasMaxLength(20);
              this.Property(t => t.ExchangeTime).HasColumnName("ExchangeTime");
              this.Property(t => t.RecordBy).HasColumnName("RecordBy").IsRequired().HasMaxLength(50);
              this.Property(t => t.CreatedOn).HasColumnName("CreatedOn");
              this.Property(t => t.CreatedBy).HasColumnName("CreatedBy").HasMaxLength(50);
              this.Property(t => t.LastUpdatedOn).HasColumnName("LastUpdatedOn");
              this.Property(t => t.LastUpdatedBy).HasColumnName("LastUpdatedBy").HasMaxLength(50);
              this.HasRequired(t => t.MailPostBagInfo).WithMany(t => t.MailExchangeBagLogs).HasForeignKey(d => d.PostBagNumber);
              this.HasRequired(t => t.MailPostBagInfo1).WithMany(t => t.MailExchangeBagLogs1).HasForeignKey(d => d.NewPostBagNumber);
         }
    }
}
