//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Context
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    using LMS.Data.Entity;
    
    
    internal partial class MailReturnGoodsLog_Mapping : EntityTypeConfiguration<MailReturnGoodsLog>
    {
        public MailReturnGoodsLog_Mapping()
        {                        
              this.HasKey(t => t.ID);        
              this.ToTable("MailReturnGoodsLogs");
              this.Property(t => t.ID).HasColumnName("ID");
              this.Property(t => t.TrackNumber).HasColumnName("TrackNumber").IsRequired().HasMaxLength(20);
              this.Property(t => t.ReasonType).HasColumnName("ReasonType");
              this.Property(t => t.ReturnBy).HasColumnName("ReturnBy").IsRequired().HasMaxLength(50);
              this.Property(t => t.ReturnOn).HasColumnName("ReturnOn");
              this.Property(t => t.CreatedOn).HasColumnName("CreatedOn");
              this.Property(t => t.CreatedBy).HasColumnName("CreatedBy").HasMaxLength(50);
              this.Property(t => t.LastUpdatedOn).HasColumnName("LastUpdatedOn");
              this.Property(t => t.LastUpdatedBy).HasColumnName("LastUpdatedBy").HasMaxLength(50);
              this.Property(t => t.TrackStatus).HasColumnName("TrackStatus");
              this.Property(t => t.PostBagNumber).HasColumnName("PostBagNumber").HasMaxLength(20);
              this.HasOptional(t => t.MailPostBagInfo).WithMany(t => t.MailReturnGoodsLogs).HasForeignKey(d => d.PostBagNumber);
         }
    }
}
