//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Context
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    using LMS.Data.Entity;
    
    
    internal partial class MailTotalPackageInfo_Mapping : EntityTypeConfiguration<MailTotalPackageInfo>
    {
        public MailTotalPackageInfo_Mapping()
        {                        
              this.HasKey(t => t.MailTotalPackageNumber);        
              this.ToTable("MailTotalPackageInfos");
              this.Property(t => t.MailTotalPackageNumber).HasColumnName("MailTotalPackageNumber").IsRequired().HasMaxLength(20);
              this.Property(t => t.TotalPackageNumber).HasColumnName("TotalPackageNumber").IsRequired().HasMaxLength(40);
              this.Property(t => t.ScanTime).HasColumnName("ScanTime");
              this.Property(t => t.FZFlightNo).HasColumnName("FZFlightNo").HasMaxLength(50);
              this.Property(t => t.FuZhouDepartureTime).HasColumnName("FuZhouDepartureTime");
              this.Property(t => t.TaiWanArrivedTime).HasColumnName("TaiWanArrivedTime");
              this.Property(t => t.TWFlightNo).HasColumnName("TWFlightNo").HasMaxLength(50);
              this.Property(t => t.TaiWanDepartureTime).HasColumnName("TaiWanDepartureTime");
              this.Property(t => t.ToArrivedTime).HasColumnName("ToArrivedTime");
              this.Property(t => t.CreatedOn).HasColumnName("CreatedOn");
              this.Property(t => t.CreatedBy).HasColumnName("CreatedBy").HasMaxLength(50);
              this.Property(t => t.LastUpdatedOn).HasColumnName("LastUpdatedOn");
              this.Property(t => t.LastUpdatedBy).HasColumnName("LastUpdatedBy").HasMaxLength(50);
              this.Property(t => t.TrackStatus).HasColumnName("TrackStatus");
              this.Property(t => t.ShortNumber).HasColumnName("ShortNumber");
              this.Property(t => t.FZFlightType).HasColumnName("FZFlightType");
         }
    }
}
