//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Context
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    using LMS.Data.Entity;
    
    
    internal partial class MoneyChangeTypeInfo_Mapping : EntityTypeConfiguration<MoneyChangeTypeInfo>
    {
        public MoneyChangeTypeInfo_Mapping()
        {                        
              this.HasKey(t => t.MoneyChangeTypeID);        
              this.ToTable("MoneyChangeTypeInfos");
              this.Property(t => t.MoneyChangeTypeID).HasColumnName("MoneyChangeTypeID");
              this.Property(t => t.MoneyChangeTypeShortName).HasColumnName("MoneyChangeTypeShortName").HasMaxLength(50);
              this.Property(t => t.MoneyChangeTypeName).HasColumnName("MoneyChangeTypeName").HasMaxLength(500);
              this.Property(t => t.MoneyFlow).HasColumnName("MoneyFlow");
              this.Property(t => t.Remark).HasColumnName("Remark").HasMaxLength(500);
              this.Property(t => t.Status).HasColumnName("Status");
         }
    }
}
