//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Context
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    using LMS.Data.Entity;
    
    
    internal partial class MouthCountry_Mapping : EntityTypeConfiguration<MouthCountry>
    {
        public MouthCountry_Mapping()
        {                        
              this.HasKey(t => t.MouthId);        
              this.ToTable("MouthCountries");
              this.Property(t => t.MouthId).HasColumnName("MouthId");
              this.Property(t => t.MouthNumber).HasColumnName("MouthNumber");
              this.Property(t => t.MouthName).HasColumnName("MouthName").IsRequired().HasMaxLength(50);
              this.Property(t => t.CountryCode).HasColumnName("CountryCode").IsRequired().HasMaxLength(5);
              this.HasRequired(t => t.Country).WithMany(t => t.MouthCountries).HasForeignKey(d => d.CountryCode);
         }
    }
}
