//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Context
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    using LMS.Data.Entity;
    
    
    internal partial class PaymentType_Mapping : EntityTypeConfiguration<PaymentType>
    {
        public PaymentType_Mapping()
        {                        
              this.HasKey(t => t.PaymentTypeID);        
              this.ToTable("PaymentTypes");
              this.Property(t => t.PaymentTypeID).HasColumnName("PaymentTypeID");
              this.Property(t => t.PaymentName).HasColumnName("PaymentName").HasMaxLength(10);
              this.Property(t => t.Remark).HasColumnName("Remark").HasMaxLength(500);
              this.Property(t => t.Status).HasColumnName("Status");
              this.Property(t => t.CreatedOn).HasColumnName("CreatedOn");
              this.Property(t => t.CreatedBy).HasColumnName("CreatedBy").HasMaxLength(50);
              this.Property(t => t.LastUpdatedOn).HasColumnName("LastUpdatedOn");
              this.Property(t => t.LastUpdatedBy).HasColumnName("LastUpdatedBy").HasMaxLength(50);
         }
    }
}
