//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Context
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    using LMS.Data.Entity;
    
    
    internal partial class ReceivingExpenseInfo_Mapping : EntityTypeConfiguration<ReceivingExpenseInfo>
    {
        public ReceivingExpenseInfo_Mapping()
        {                        
              this.HasKey(t => t.ReceivingExpenseInfoID);        
              this.ToTable("ReceivingExpenseInfos");
              this.Property(t => t.ReceivingExpenseInfoID).HasColumnName("ReceivingExpenseInfoID");
              this.Property(t => t.ReceivingExpenseID).HasColumnName("ReceivingExpenseID");
              this.Property(t => t.FeeTypeID).HasColumnName("FeeTypeID");
              this.Property(t => t.Amount).HasColumnName("Amount");
              this.Property(t => t.OperationType).HasColumnName("OperationType");
              this.Property(t => t.CreatedOn).HasColumnName("CreatedOn");
              this.Property(t => t.CreatedBy).HasColumnName("CreatedBy").HasMaxLength(50);
              this.Property(t => t.LastUpdatedOn).HasColumnName("LastUpdatedOn");
              this.Property(t => t.LastUpdatedBy).HasColumnName("LastUpdatedBy").HasMaxLength(50);
              this.Property(t => t.ReceivingBillID).HasColumnName("ReceivingBillID").HasMaxLength(20);
              this.HasOptional(t => t.FeeType).WithMany(t => t.ReceivingExpenseInfos).HasForeignKey(d => d.FeeTypeID);
              this.HasOptional(t => t.ReceivingExpens).WithMany(t => t.ReceivingExpenseInfos).HasForeignKey(d => d.ReceivingExpenseID);
         }
    }
}
