//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Context
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    using LMS.Data.Entity;
    
    
    internal partial class ReceivingBill_Mapping : EntityTypeConfiguration<ReceivingBill>
    {
        public ReceivingBill_Mapping()
        {                        
              this.HasKey(t => t.ReceivingBillID);        
              this.ToTable("ReceivingBills");
              this.Property(t => t.ReceivingBillID).HasColumnName("ReceivingBillID").IsRequired().HasMaxLength(20);
              this.Property(t => t.CustomerCode).HasColumnName("CustomerCode").HasMaxLength(20);
              this.Property(t => t.CustomerName).HasColumnName("CustomerName").HasMaxLength(128);
              this.Property(t => t.ReceivingBillDate).HasColumnName("ReceivingBillDate");
              this.Property(t => t.ReceivingBillAuditor).HasColumnName("ReceivingBillAuditor").HasMaxLength(50);
              this.Property(t => t.BillStartTime).HasColumnName("BillStartTime");
              this.Property(t => t.BillEndTime).HasColumnName("BillEndTime");
              this.Property(t => t.ShippingMethodID).HasColumnName("ShippingMethodID");
              this.Property(t => t.CountryCode).HasColumnName("CountryCode").HasMaxLength(5);
              this.Property(t => t.Search).HasColumnName("Search");
              this.Property(t => t.SearchValue).HasColumnName("SearchValue");
              this.Property(t => t.Status).HasColumnName("Status");
              this.Property(t => t.JobRemark).HasColumnName("JobRemark").HasMaxLength(500);
         }
    }
}
