//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Context
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    using LMS.Data.Entity;
    
    
    internal partial class ReceivingExpens_Mapping : EntityTypeConfiguration<ReceivingExpens>
    {
        public ReceivingExpens_Mapping()
        {                        
              this.HasKey(t => t.ReceivingExpenseID);        
              this.ToTable("ReceivingExpenses");
              this.Property(t => t.ReceivingExpenseID).HasColumnName("ReceivingExpenseID");
              this.Property(t => t.WayBillNumber).HasColumnName("WayBillNumber").HasMaxLength(20);
              this.Property(t => t.CustomerOrderNumber).HasColumnName("CustomerOrderNumber").HasMaxLength(50);
              this.Property(t => t.FinancialNote).HasColumnName("FinancialNote").HasMaxLength(4000);
              this.Property(t => t.Status).HasColumnName("Status");
              this.Property(t => t.Auditor).HasColumnName("Auditor").HasMaxLength(50);
              this.Property(t => t.AuditorDate).HasColumnName("AuditorDate");
              this.Property(t => t.CreatedOn).HasColumnName("CreatedOn");
              this.Property(t => t.CreatedBy).HasColumnName("CreatedBy").HasMaxLength(50);
              this.Property(t => t.LastUpdatedOn).HasColumnName("LastUpdatedOn");
              this.Property(t => t.LastUpdatedBy).HasColumnName("LastUpdatedBy").HasMaxLength(50);
              this.Property(t => t.IsNoGet).HasColumnName("IsNoGet");
              this.Property(t => t.AcceptanceDate).HasColumnName("AcceptanceDate");
              this.HasOptional(t => t.WayBillInfo).WithMany(t => t.ReceivingExpenses).HasForeignKey(d => d.WayBillNumber);
         }
    }
}
