//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Context
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    using LMS.Data.Entity;
    
    
    internal partial class SequenceNumber_Mapping : EntityTypeConfiguration<SequenceNumber>
    {
        public SequenceNumber_Mapping()
        {                        
              this.HasKey(t => t.Code);        
              this.ToTable("SequenceNumbers");
              this.Property(t => t.ID).HasColumnName("ID").HasDatabaseGeneratedOption(new Nullable<DatabaseGeneratedOption>(DatabaseGeneratedOption.Identity));
              this.Property(t => t.Code).HasColumnName("Code").IsRequired().HasMaxLength(10);
              this.Property(t => t.Prefix).HasColumnName("Prefix").HasMaxLength(5);
              this.Property(t => t.DateType).HasColumnName("DateType").HasMaxLength(8);
              this.Property(t => t.Infix).HasColumnName("Infix").HasMaxLength(5);
              this.Property(t => t.IndexLength).HasColumnName("IndexLength");
              this.Property(t => t.Suffix).HasColumnName("Suffix").HasMaxLength(5);
              this.Property(t => t.MaxDate).HasColumnName("MaxDate").HasMaxLength(8);
              this.Property(t => t.MaxIndex).HasColumnName("MaxIndex");
              this.Property(t => t.CurrentMaxValue).HasColumnName("CurrentMaxValue").HasDatabaseGeneratedOption(new Nullable<DatabaseGeneratedOption>(DatabaseGeneratedOption.Computed)).HasMaxLength(4000);
         }
    }
}
