//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Context
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    using LMS.Data.Entity;
    
    
    internal partial class SettlementInfo_Mapping : EntityTypeConfiguration<SettlementInfo>
    {
        public SettlementInfo_Mapping()
        {                        
              this.HasKey(t => t.SettlementNumber);        
              this.ToTable("SettlementInfos");
              this.Property(t => t.SettlementNumber).HasColumnName("SettlementNumber").IsRequired().HasMaxLength(20);
              this.Property(t => t.CustomerCode).HasColumnName("CustomerCode").IsRequired().HasMaxLength(20);
              this.Property(t => t.TotalNumber).HasColumnName("TotalNumber");
              this.Property(t => t.TotalWeight).HasColumnName("TotalWeight");
              this.Property(t => t.TotalSettleWeight).HasColumnName("TotalSettleWeight");
              this.Property(t => t.TotalFee).HasColumnName("TotalFee");
              this.Property(t => t.Status).HasColumnName("Status");
              this.Property(t => t.SalesMan).HasColumnName("SalesMan").HasMaxLength(50);
              this.Property(t => t.SalesManTel).HasColumnName("SalesManTel").HasMaxLength(50);
              this.Property(t => t.SettlementBy).HasColumnName("SettlementBy").HasMaxLength(50);
              this.Property(t => t.SettlementOn).HasColumnName("SettlementOn");
              this.Property(t => t.CreatedBy).HasColumnName("CreatedBy").HasMaxLength(50);
              this.Property(t => t.CreatedOn).HasColumnName("CreatedOn");
              this.Property(t => t.LastUpdatedBy).HasColumnName("LastUpdatedBy").HasMaxLength(50);
              this.Property(t => t.LastUpdatedOn).HasColumnName("LastUpdatedOn");
         }
    }
}
