//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Context
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    using LMS.Data.Entity;
    
    
    internal partial class ShippingInfo_Mapping : EntityTypeConfiguration<ShippingInfo>
    {
        public ShippingInfo_Mapping()
        {                        
              this.HasKey(t => t.ShippingInfoID);        
              this.ToTable("ShippingInfos");
              this.Property(t => t.ShippingInfoID).HasColumnName("ShippingInfoID");
              this.Property(t => t.CountryCode).HasColumnName("CountryCode").HasMaxLength(5);
              this.Property(t => t.ShippingFirstName).HasColumnName("ShippingFirstName").HasMaxLength(200);
              this.Property(t => t.ShippingLastName).HasColumnName("ShippingLastName").HasMaxLength(200);
              this.Property(t => t.ShippingCompany).HasColumnName("ShippingCompany").HasMaxLength(200);
              this.Property(t => t.ShippingAddress).HasColumnName("ShippingAddress").HasMaxLength(200);
              this.Property(t => t.ShippingCity).HasColumnName("ShippingCity").HasMaxLength(200);
              this.Property(t => t.ShippingState).HasColumnName("ShippingState").HasMaxLength(200);
              this.Property(t => t.ShippingZip).HasColumnName("ShippingZip").HasMaxLength(200);
              this.Property(t => t.ShippingPhone).HasColumnName("ShippingPhone").HasMaxLength(200);
              this.Property(t => t.ShippingTaxId).HasColumnName("ShippingTaxId").HasMaxLength(50);
              this.Property(t => t.ShippingAddress1).HasColumnName("ShippingAddress1").HasMaxLength(200);
              this.Property(t => t.ShippingAddress2).HasColumnName("ShippingAddress2").HasMaxLength(200);
         }
    }
}
