//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Context
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    using LMS.Data.Entity;
    
    
    internal partial class Task_Mapping : EntityTypeConfiguration<Task>
    {
        public Task_Mapping()
        {                        
              this.HasKey(t => t.TaskID);        
              this.ToTable("Task");
              this.Property(t => t.TaskID).HasColumnName("TaskID");
              this.Property(t => t.TaskType).HasColumnName("TaskType");
              this.Property(t => t.TaskKey).HasColumnName("TaskKey").IsRequired().HasMaxLength(256);
              this.Property(t => t.Status).HasColumnName("Status");
              this.Property(t => t.Body).HasColumnName("Body").IsRequired();
              this.Property(t => t.Times).HasColumnName("Times");
              this.Property(t => t.Error).HasColumnName("Error");
              this.Property(t => t.CreateOn).HasColumnName("CreateOn");
         }
    }
}
