//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Context
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    using LMS.Data.Entity;
    
    
    internal partial class TotalPackageOutStorageRelationalInfo_Mapping : EntityTypeConfiguration<TotalPackageOutStorageRelationalInfo>
    {
        public TotalPackageOutStorageRelationalInfo_Mapping()
        {                        
              this.HasKey(t => t.ID);        
              this.ToTable("TotalPackageOutStorageRelationalInfos");
              this.Property(t => t.ID).HasColumnName("ID");
              this.Property(t => t.TotalPackageNumber).HasColumnName("TotalPackageNumber").IsRequired().HasMaxLength(20);
              this.Property(t => t.OutStorageID).HasColumnName("OutStorageID").HasMaxLength(16);
              this.Property(t => t.CreatedOn).HasColumnName("CreatedOn");
         }
    }
}
