//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Context
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    using LMS.Data.Entity;
    
    
    internal partial class TotalPackageInfo_Mapping : EntityTypeConfiguration<TotalPackageInfo>
    {
        public TotalPackageInfo_Mapping()
        {                        
              this.HasKey(t => t.TotalPackageNumber);        
              this.ToTable("TotalPackageInfos");
              this.Property(t => t.TotalPackageNumber).HasColumnName("TotalPackageNumber").IsRequired().HasMaxLength(20);
              this.Property(t => t.VenderCode).HasColumnName("VenderCode").IsRequired().HasMaxLength(12);
              this.Property(t => t.VenderName).HasColumnName("VenderName").IsRequired().HasMaxLength(100);
              this.Property(t => t.TotalQty).HasColumnName("TotalQty");
              this.Property(t => t.TotalWeight).HasColumnName("TotalWeight");
              this.Property(t => t.TotalVotes).HasColumnName("TotalVotes");
              this.Property(t => t.Remark).HasColumnName("Remark").HasMaxLength(200);
              this.Property(t => t.CreatedOn).HasColumnName("CreatedOn");
              this.Property(t => t.CreatedBy).HasColumnName("CreatedBy").HasMaxLength(50);
              this.Property(t => t.LastUpdatedOn).HasColumnName("LastUpdatedOn");
              this.Property(t => t.LastUpdatedBy).HasColumnName("LastUpdatedBy").HasMaxLength(50);
         }
    }
}
