//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Context
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    using LMS.Data.Entity;
    
    
    internal partial class TrackingNumberInfo_Mapping : EntityTypeConfiguration<TrackingNumberInfo>
    {
        public TrackingNumberInfo_Mapping()
        {                        
              this.HasKey(t => t.TrackingNumberID);        
              this.ToTable("TrackingNumberInfos");
              this.Property(t => t.TrackingNumberID).HasColumnName("TrackingNumberID").IsRequired().HasMaxLength(20);
              this.Property(t => t.ShippingMethodID).HasColumnName("ShippingMethodID");
              this.Property(t => t.ApplianceCountry).HasColumnName("ApplianceCountry").IsRequired();
              this.Property(t => t.StartSegment).HasColumnName("StartSegment").HasMaxLength(20);
              this.Property(t => t.EndSegment).HasColumnName("EndSegment").HasMaxLength(20);
              this.Property(t => t.StartCharacter).HasColumnName("StartCharacter").HasMaxLength(50);
              this.Property(t => t.EndCharacter).HasColumnName("EndCharacter").HasMaxLength(50);
              this.Property(t => t.Status).HasColumnName("Status");
              this.Property(t => t.Remarks).HasColumnName("Remarks");
              this.Property(t => t.CreatedBy).HasColumnName("CreatedBy").IsRequired().HasMaxLength(50);
              this.Property(t => t.CreatedNo).HasColumnName("CreatedNo");
              this.Property(t => t.LastUpdatedBy).HasColumnName("LastUpdatedBy").IsRequired().HasMaxLength(50);
              this.Property(t => t.LastUpdateOn).HasColumnName("LastUpdateOn");
         }
    }
}
