//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Context
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    using LMS.Data.Entity;
    
    
    internal partial class TrackingNumberDetailInfo_Mapping : EntityTypeConfiguration<TrackingNumberDetailInfo>
    {
        public TrackingNumberDetailInfo_Mapping()
        {                        
              this.HasKey(t => t.TrackingNumberDetailID);        
              this.ToTable("TrackingNumberDetailInfos");
              this.Property(t => t.TrackingNumberDetailID).HasColumnName("TrackingNumberDetailID");
              this.Property(t => t.TrackingNumberID).HasColumnName("TrackingNumberID").IsRequired().HasMaxLength(20);
              this.Property(t => t.TrackingNumber).HasColumnName("TrackingNumber").IsRequired().HasMaxLength(50);
              this.Property(t => t.Status).HasColumnName("Status");
              this.Property(t => t.WayBillNumber).HasColumnName("WayBillNumber").IsRequired().HasMaxLength(20);
              this.HasRequired(t => t.TrackingNumberInfo).WithMany(t => t.TrackingNumberDetailInfos).HasForeignKey(d => d.TrackingNumberID);
         }
    }
}
