//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Context
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    using LMS.Data.Entity;
    
    
    internal partial class VenderFeeLog_Mapping : EntityTypeConfiguration<VenderFeeLog>
    {
        public VenderFeeLog_Mapping()
        {                        
              this.HasKey(t => t.WayBillNumber);        
              this.ToTable("VenderFeeLog");
              this.Property(t => t.WayBillNumber).HasColumnName("WayBillNumber").IsRequired().HasMaxLength(20);
              this.Property(t => t.Freight).HasColumnName("Freight");
              this.Property(t => t.FuelCharge).HasColumnName("FuelCharge");
              this.Property(t => t.Register).HasColumnName("Register");
              this.Property(t => t.Surcharge).HasColumnName("Surcharge");
              this.Property(t => t.CreatedOn).HasColumnName("CreatedOn");
              this.Property(t => t.CreatedBy).HasColumnName("CreatedBy").HasMaxLength(50);
              this.Property(t => t.Remark).HasColumnName("Remark").HasMaxLength(500);
              this.Property(t => t.GoodsTypeID).HasColumnName("GoodsTypeID");
              this.Property(t => t.SettleWeight).HasColumnName("SettleWeight");
         }
    }
}
