//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Context
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    using LMS.Data.Entity;
    
    
    internal partial class WayBillEventLog_Mapping : EntityTypeConfiguration<WayBillEventLog>
    {
        public WayBillEventLog_Mapping()
        {                        
              this.HasKey(t => t.WayBillEventLogId);        
              this.ToTable("WayBillEventLogs");
              this.Property(t => t.WayBillEventLogId).HasColumnName("WayBillEventLogId");
              this.Property(t => t.WayBillNumber).HasColumnName("WayBillNumber").IsRequired().HasMaxLength(20);
              this.Property(t => t.EventCode).HasColumnName("EventCode");
              this.Property(t => t.EventDate).HasColumnName("EventDate");
              this.Property(t => t.Operator).HasColumnName("Operator").IsRequired().HasMaxLength(50);
              this.Property(t => t.Description).HasColumnName("Description").HasMaxLength(50);
              this.Property(t => t.TrackingLogCreated).HasColumnName("TrackingLogCreated");
              this.Property(t => t.TrackingLogProgress).HasColumnName("TrackingLogProgress");
              this.Property(t => t.LastUpdatedOn).HasColumnName("LastUpdatedOn");
              this.Property(t => t.Remarks).HasColumnName("Remarks").HasMaxLength(500);
         }
    }
}
