//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Context
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    using LMS.Data.Entity;
    
    
    internal partial class WayBillInfo_Mapping : EntityTypeConfiguration<WayBillInfo>
    {
        public WayBillInfo_Mapping()
        {                        
              this.HasKey(t => t.WayBillNumber);        
              this.ToTable("WayBillInfos");
              this.Property(t => t.WayBillNumber).HasColumnName("WayBillNumber").IsRequired().HasMaxLength(20);
              this.Property(t => t.CustomerOrderID).HasColumnName("CustomerOrderID");
              this.Property(t => t.CustomerCode).HasColumnName("CustomerCode").HasMaxLength(20);
              this.Property(t => t.TrackingNumber).HasColumnName("TrackingNumber").HasMaxLength(50);
              this.Property(t => t.RawTrackingNumber).HasColumnName("RawTrackingNumber").HasMaxLength(50);
              this.Property(t => t.Weight).HasColumnName("Weight");
              this.Property(t => t.SettleWeight).HasColumnName("SettleWeight");
              this.Property(t => t.Length).HasColumnName("Length");
              this.Property(t => t.Width).HasColumnName("Width");
              this.Property(t => t.Height).HasColumnName("Height");
              this.Property(t => t.GoodsTypeID).HasColumnName("GoodsTypeID");
              this.Property(t => t.IsReturn).HasColumnName("IsReturn");
              this.Property(t => t.IsHold).HasColumnName("IsHold");
              this.Property(t => t.IsBattery).HasColumnName("IsBattery");
              this.Property(t => t.Status).HasColumnName("Status");
              this.Property(t => t.OutStorageID).HasColumnName("OutStorageID").HasMaxLength(16);
              this.Property(t => t.InStorageID).HasColumnName("InStorageID").HasMaxLength(16);
              this.Property(t => t.ShippingInfoID).HasColumnName("ShippingInfoID");
              this.Property(t => t.SenderInfoID).HasColumnName("SenderInfoID");
              this.Property(t => t.CountryCode).HasColumnName("CountryCode").HasMaxLength(5);
              this.Property(t => t.InsuredID).HasColumnName("InsuredID");
              this.Property(t => t.AbnormalID).HasColumnName("AbnormalID");
              this.Property(t => t.InShippingMethodID).HasColumnName("InShippingMethodID");
              this.Property(t => t.OutShippingMethodID).HasColumnName("OutShippingMethodID");
              this.Property(t => t.InShippingMethodName).HasColumnName("InShippingMethodName").HasMaxLength(100);
              this.Property(t => t.OutShippingMethodName).HasColumnName("OutShippingMethodName").HasMaxLength(100);
              this.Property(t => t.CreatedOn).HasColumnName("CreatedOn");
              this.Property(t => t.CreatedBy).HasColumnName("CreatedBy").HasMaxLength(50);
              this.Property(t => t.LastUpdatedOn).HasColumnName("LastUpdatedOn");
              this.Property(t => t.LastUpdatedBy).HasColumnName("LastUpdatedBy").HasMaxLength(50);
              this.Property(t => t.TransferOrderDate).HasColumnName("TransferOrderDate");
              this.Property(t => t.VenderCode).HasColumnName("VenderCode").HasMaxLength(50);
              this.Property(t => t.CustomerOrderNumber).HasColumnName("CustomerOrderNumber").IsRequired().HasMaxLength(50);
              this.Property(t => t.InStorageCreatedOn).HasColumnName("InStorageCreatedOn");
              this.Property(t => t.OutStorageCreatedOn).HasColumnName("OutStorageCreatedOn");
              this.Property(t => t.TrueTrackingNumber).HasColumnName("TrueTrackingNumber").HasMaxLength(50);
              this.Property(t => t.EnableTariffPrepay).HasColumnName("EnableTariffPrepay");
              this.HasOptional(t => t.AbnormalWayBillLog).WithMany(t => t.WayBillInfos).HasForeignKey(d => d.AbnormalID);
              this.HasOptional(t => t.CustomerOrderInfo).WithMany(t => t.WayBillInfos).HasForeignKey(d => d.CustomerOrderID);
              this.HasOptional(t => t.GoodsTypeInfo).WithMany(t => t.WayBillInfos).HasForeignKey(d => d.GoodsTypeID);
              this.HasOptional(t => t.InStorageInfo).WithMany(t => t.WayBillInfos).HasForeignKey(d => d.InStorageID);
              this.HasOptional(t => t.InsuredCalculation).WithMany(t => t.WayBillInfos).HasForeignKey(d => d.InsuredID);
              this.HasOptional(t => t.SenderInfo).WithMany(t => t.WayBillInfos).HasForeignKey(d => d.SenderInfoID);
              this.HasOptional(t => t.ShippingInfo).WithMany(t => t.WayBillInfos).HasForeignKey(d => d.ShippingInfoID);
              this.HasOptional(t => t.OutStorageInfo).WithMany(t => t.WayBillInfos).HasForeignKey(d => d.OutStorageID);
         }
    }
}
