//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Context
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    using LMS.Data.Entity;
    
    
    internal partial class WayBillChangeLog_Mapping : EntityTypeConfiguration<WayBillChangeLog>
    {
        public WayBillChangeLog_Mapping()
        {                        
              this.HasKey(t => t.WayBillChangeLogID);        
              this.ToTable("WayBillChangeLogs");
              this.Property(t => t.WayBillChangeLogID).HasColumnName("WayBillChangeLogID");
              this.Property(t => t.CustomerOrderID).HasColumnName("CustomerOrderID");
              this.Property(t => t.CustomerOrderNumber).HasColumnName("CustomerOrderNumber").IsRequired().HasMaxLength(50);
              this.Property(t => t.WayBillNumber).HasColumnName("WayBillNumber").IsRequired().HasMaxLength(20);
              this.Property(t => t.OriginalWayBillNumber).HasColumnName("OriginalWayBillNumber").IsRequired().HasMaxLength(20);
              this.Property(t => t.ChangeType).HasColumnName("ChangeType");
              this.Property(t => t.ChangeReason).HasColumnName("ChangeReason").HasMaxLength(500);
              this.Property(t => t.CreatedOn).HasColumnName("CreatedOn");
              this.Property(t => t.CreatedBy).HasColumnName("CreatedBy").HasMaxLength(50);
              this.Property(t => t.LastUpdatedOn).HasColumnName("LastUpdatedOn");
              this.Property(t => t.LastUpdatedBy).HasColumnName("LastUpdatedBy").HasMaxLength(50);
         }
    }
}
