//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Context
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    using LMS.Data.Entity;
    
    
    internal partial class WayBillTemplate_Mapping : EntityTypeConfiguration<WayBillTemplate>
    {
        public WayBillTemplate_Mapping()
        {                        
              this.HasKey(t => t.WayBillTemplateId);        
              this.ToTable("WayBillTemplates");
              this.Property(t => t.WayBillTemplateId).HasColumnName("WayBillTemplateId");
              this.Property(t => t.TemplateName).HasColumnName("TemplateName").IsRequired().HasMaxLength(50);
              this.Property(t => t.TemplateTypeId).HasColumnName("TemplateTypeId").IsRequired().HasMaxLength(20);
              this.Property(t => t.ShippingMethodId).HasColumnName("ShippingMethodId");
              this.Property(t => t.Status).HasColumnName("Status");
              this.Property(t => t.TemplateContent).HasColumnName("TemplateContent");
              this.Property(t => t.Remark).HasColumnName("Remark").HasMaxLength(200);
              this.Property(t => t.CreatedOn).HasColumnName("CreatedOn");
              this.Property(t => t.CreatedBy).HasColumnName("CreatedBy").IsFixedLength().HasMaxLength(10);
              this.Property(t => t.LastUpdatedOn).HasColumnName("LastUpdatedOn");
              this.Property(t => t.LastUpdatedBy).HasColumnName("LastUpdatedBy").HasMaxLength(50);
              this.Property(t => t.RowNumber).HasColumnName("RowNumber");
              this.Property(t => t.ColumnNumber).HasColumnName("ColumnNumber");
              this.Property(t => t.TemplateHeadId).HasColumnName("TemplateHeadId");
              this.Property(t => t.TemplateContentId).HasColumnName("TemplateContentId");
              this.Property(t => t.LinkMode).HasColumnName("LinkMode");
              this.Property(t => t.Countries).HasColumnName("Countries");
         }
    }
}
