//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data.Context
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    using LMS.Data.Entity;
    
    
    internal partial class WayBillTemplateInfo_Mapping : EntityTypeConfiguration<WayBillTemplateInfo>
    {
        public WayBillTemplateInfo_Mapping()
        {                        
              this.HasKey(t => t.TemplateModelId);        
              this.ToTable("WayBillTemplateInfos");
              this.Property(t => t.TemplateModelId).HasColumnName("TemplateModelId");
              this.Property(t => t.TemplateType).HasColumnName("TemplateType");
              this.Property(t => t.TemplateName).HasColumnName("TemplateName").IsRequired().HasMaxLength(50);
              this.Property(t => t.TemplateContent).HasColumnName("TemplateContent").IsRequired();
              this.Property(t => t.Remarks).HasColumnName("Remarks").HasMaxLength(500);
              this.Property(t => t.Status).HasColumnName("Status");
              this.Property(t => t.CreatedOn).HasColumnName("CreatedOn");
              this.Property(t => t.CreatedBy).HasColumnName("CreatedBy").IsRequired().HasMaxLength(50);
              this.Property(t => t.LastUpdatedOn).HasColumnName("LastUpdatedOn");
              this.Property(t => t.LastUpdatedBy).HasColumnName("LastUpdatedBy").IsRequired().HasMaxLength(50);
         }
    }
}
