//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.WebAPI.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LMS.WebAPI.Client.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 提交成功 的本地化字符串。
        /// </summary>
        internal static string Error0000 {
            get {
                return ResourceManager.GetString("Error0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请求超过次数 的本地化字符串。
        /// </summary>
        internal static string Error10000 {
            get {
                return ResourceManager.GetString("Error10000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交失败 的本地化字符串。
        /// </summary>
        internal static string Error1001 {
            get {
                return ResourceManager.GetString("Error1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接口UserID或ApiKey错误 的本地化字符串。
        /// </summary>
        internal static string Error1002 {
            get {
                return ResourceManager.GetString("Error1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 签名错误 的本地化字符串。
        /// </summary>
        internal static string Error1003 {
            get {
                return ResourceManager.GetString("Error1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数错误 的本地化字符串。
        /// </summary>
        internal static string Error1004 {
            get {
                return ResourceManager.GetString("Error1004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手机号码错误 的本地化字符串。
        /// </summary>
        internal static string Error1005 {
            get {
                return ResourceManager.GetString("Error1005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到数据 的本地化字符串。
        /// </summary>
        internal static string Error1006 {
            get {
                return ResourceManager.GetString("Error1006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部分成功 的本地化字符串。
        /// </summary>
        internal static string Error1011 {
            get {
                return ResourceManager.GetString("Error1011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日期格式错误 的本地化字符串。
        /// </summary>
        internal static string Error2001 {
            get {
                return ResourceManager.GetString("Error2001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 长度超过限制 的本地化字符串。
        /// </summary>
        internal static string Error2002 {
            get {
                return ResourceManager.GetString("Error2002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户编号不存在 的本地化字符串。
        /// </summary>
        internal static string Error2003 {
            get {
                return ResourceManager.GetString("Error2003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单号存在重复 的本地化字符串。
        /// </summary>
        internal static string Error2004 {
            get {
                return ResourceManager.GetString("Error2004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单号已存在 的本地化字符串。
        /// </summary>
        internal static string Error2005 {
            get {
                return ResourceManager.GetString("Error2005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该运输方式没可用跟踪号 的本地化字符串。
        /// </summary>
        internal static string Error2006 {
            get {
                return ResourceManager.GetString("Error2006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 跟踪号已存在 的本地化字符串。
        /// </summary>
        internal static string Error2007 {
            get {
                return ResourceManager.GetString("Error2007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未开通关税预付权限，请联系业务 的本地化字符串。
        /// </summary>
        internal static string Error2008 {
            get {
                return ResourceManager.GetString("Error2008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重量必须大于零 的本地化字符串。
        /// </summary>
        internal static string Error2009 {
            get {
                return ResourceManager.GetString("Error2009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该运输方式不发送到此国家 的本地化字符串。
        /// </summary>
        internal static string Error2010 {
            get {
                return ResourceManager.GetString("Error2010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 申报信息备注格式不正确 的本地化字符串。
        /// </summary>
        internal static string Error2011 {
            get {
                return ResourceManager.GetString("Error2011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收件人电话格式不正确 的本地化字符串。
        /// </summary>
        internal static string Error2012 {
            get {
                return ResourceManager.GetString("Error2012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单号不能超过25个字符 的本地化字符串。
        /// </summary>
        internal static string Error2013 {
            get {
                return ResourceManager.GetString("Error2013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮编不能为空 的本地化字符串。
        /// </summary>
        internal static string Error2014 {
            get {
                return ResourceManager.GetString("Error2014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 州/省不能为空 的本地化字符串。
        /// </summary>
        internal static string Error2015 {
            get {
                return ResourceManager.GetString("Error2015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 城市不能为空 的本地化字符串。
        /// </summary>
        internal static string Error2016 {
            get {
                return ResourceManager.GetString("Error2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 件数不能为0 的本地化字符串。
        /// </summary>
        internal static string Error2017 {
            get {
                return ResourceManager.GetString("Error2017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运输方式不存在或未启用 的本地化字符串。
        /// </summary>
        internal static string Error2018 {
            get {
                return ResourceManager.GetString("Error2018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册失败 的本地化字符串。
        /// </summary>
        internal static string Error2019 {
            get {
                return ResourceManager.GetString("Error2019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名不能为空,只能为数字和字母,排除特殊字符如 ! # % 的本地化字符串。
        /// </summary>
        internal static string Error2020 {
            get {
                return ResourceManager.GetString("Error2020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户密码输入不能为空 的本地化字符串。
        /// </summary>
        internal static string Error2021 {
            get {
                return ResourceManager.GetString("Error2021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户确认密码输入不一致 的本地化字符串。
        /// </summary>
        internal static string Error2022 {
            get {
                return ResourceManager.GetString("Error2022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联系人不能为空 的本地化字符串。
        /// </summary>
        internal static string Error2023 {
            get {
                return ResourceManager.GetString("Error2023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联系人手机不能为空 的本地化字符串。
        /// </summary>
        internal static string Error2024 {
            get {
                return ResourceManager.GetString("Error2024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户名称不能为空 的本地化字符串。
        /// </summary>
        internal static string Error2025 {
            get {
                return ResourceManager.GetString("Error2025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email不能为空 的本地化字符串。
        /// </summary>
        internal static string Error2026 {
            get {
                return ResourceManager.GetString("Error2026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址不能为空 的本地化字符串。
        /// </summary>
        internal static string Error2027 {
            get {
                return ResourceManager.GetString("Error2027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平台来源不能为空 的本地化字符串。
        /// </summary>
        internal static string Error2028 {
            get {
                return ResourceManager.GetString("Error2028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名已存在 的本地化字符串。
        /// </summary>
        internal static string Error2029 {
            get {
                return ResourceManager.GetString("Error2029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平台异常 的本地化字符串。
        /// </summary>
        internal static string Error9999 {
            get {
                return ResourceManager.GetString("Error9999", resourceCulture);
            }
        }
    }
}
