//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Services.SF.Model {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorCode {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorCode() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LMS.Services.SF.Model.ErrorCode", typeof(ErrorCode).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 系统发生数据错误或运行时异常 的本地化字符串。
        /// </summary>
        internal static string _4001 {
            get {
                return ResourceManager.GetString("4001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报文解析错误 的本地化字符串。
        /// </summary>
        internal static string _4002 {
            get {
                return ResourceManager.GetString("4002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请求数据缺少必选项 的本地化字符串。
        /// </summary>
        internal static string _6101 {
            get {
                return ResourceManager.GetString("6101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 寄件方公司名称为空 的本地化字符串。
        /// </summary>
        internal static string _6102 {
            get {
                return ResourceManager.GetString("6102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 寄方联系人为空 的本地化字符串。
        /// </summary>
        internal static string _6103 {
            get {
                return ResourceManager.GetString("6103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 寄方所在省为空 的本地化字符串。
        /// </summary>
        internal static string _6104 {
            get {
                return ResourceManager.GetString("6104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 寄方所在城市为空 的本地化字符串。
        /// </summary>
        internal static string _6105 {
            get {
                return ResourceManager.GetString("6105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 寄件方详细地址为空 的本地化字符串。
        /// </summary>
        internal static string _6106 {
            get {
                return ResourceManager.GetString("6106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 到件方公司名称为空 的本地化字符串。
        /// </summary>
        internal static string _6107 {
            get {
                return ResourceManager.GetString("6107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 到件方联系人为空 的本地化字符串。
        /// </summary>
        internal static string _6108 {
            get {
                return ResourceManager.GetString("6108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 到件方所在省为空 的本地化字符串。
        /// </summary>
        internal static string _6109 {
            get {
                return ResourceManager.GetString("6109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 到件方所在城市为空 的本地化字符串。
        /// </summary>
        internal static string _6110 {
            get {
                return ResourceManager.GetString("6110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 到件方地址为空 的本地化字符串。
        /// </summary>
        internal static string _6111 {
            get {
                return ResourceManager.GetString("6111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 到件方国家不能为空 的本地化字符串。
        /// </summary>
        internal static string _6112 {
            get {
                return ResourceManager.GetString("6112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 到件方所在省份不能为空 的本地化字符串。
        /// </summary>
        internal static string _6113 {
            get {
                return ResourceManager.GetString("6113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须提供客户订单号 的本地化字符串。
        /// </summary>
        internal static string _6114 {
            get {
                return ResourceManager.GetString("6114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 到件方所属城市名称不能为空 的本地化字符串。
        /// </summary>
        internal static string _6115 {
            get {
                return ResourceManager.GetString("6115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 到件方所在县/区不能为空 的本地化字符串。
        /// </summary>
        internal static string _6116 {
            get {
                return ResourceManager.GetString("6116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 到件方详细地址不能为空 的本地化字符串。
        /// </summary>
        internal static string _6117 {
            get {
                return ResourceManager.GetString("6117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单号不能为空 的本地化字符串。
        /// </summary>
        internal static string _6118 {
            get {
                return ResourceManager.GetString("6118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 到件方联系电话不能为空 的本地化字符串。
        /// </summary>
        internal static string _6119 {
            get {
                return ResourceManager.GetString("6119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快递类型不能为空 的本地化字符串。
        /// </summary>
        internal static string _6120 {
            get {
                return ResourceManager.GetString("6120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 寄件方联系电话不能为空 的本地化字符串。
        /// </summary>
        internal static string _6121 {
            get {
                return ResourceManager.GetString("6121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 筛单类别不合法 的本地化字符串。
        /// </summary>
        internal static string _6122 {
            get {
                return ResourceManager.GetString("6122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运单号不能为空 的本地化字符串。
        /// </summary>
        internal static string _6123 {
            get {
                return ResourceManager.GetString("6123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 付款方式不能为空 的本地化字符串。
        /// </summary>
        internal static string _6124 {
            get {
                return ResourceManager.GetString("6124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需生成电子运单,货物名称等不能为空 的本地化字符串。
        /// </summary>
        internal static string _6125 {
            get {
                return ResourceManager.GetString("6125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 月结卡号不合法 的本地化字符串。
        /// </summary>
        internal static string _6126 {
            get {
                return ResourceManager.GetString("6126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 增值服务名不能为空 的本地化字符串。
        /// </summary>
        internal static string _6127 {
            get {
                return ResourceManager.GetString("6127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 增值服务名不合法 的本地化字符串。
        /// </summary>
        internal static string _6128 {
            get {
                return ResourceManager.GetString("6128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 付款方式不正确 的本地化字符串。
        /// </summary>
        internal static string _6129 {
            get {
                return ResourceManager.GetString("6129", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 体积参数不合法 的本地化字符串。
        /// </summary>
        internal static string _6130 {
            get {
                return ResourceManager.GetString("6130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单操作标识不合法 的本地化字符串。
        /// </summary>
        internal static string _6131 {
            get {
                return ResourceManager.GetString("6131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路由查询方式不合法 的本地化字符串。
        /// </summary>
        internal static string _6132 {
            get {
                return ResourceManager.GetString("6132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路由查询类别不合法 的本地化字符串。
        /// </summary>
        internal static string _6133 {
            get {
                return ResourceManager.GetString("6133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未传入筛单数据 的本地化字符串。
        /// </summary>
        internal static string _6134 {
            get {
                return ResourceManager.GetString("6134", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未传入订单信息 的本地化字符串。
        /// </summary>
        internal static string _6135 {
            get {
                return ResourceManager.GetString("6135", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未传入订单确认信息 的本地化字符串。
        /// </summary>
        internal static string _6136 {
            get {
                return ResourceManager.GetString("6136", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未传入请求路由信息 的本地化字符串。
        /// </summary>
        internal static string _6137 {
            get {
                return ResourceManager.GetString("6137", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代收货款金额传入错误 的本地化字符串。
        /// </summary>
        internal static string _6138 {
            get {
                return ResourceManager.GetString("6138", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代收货款金额小于 0 错误 的本地化字符串。
        /// </summary>
        internal static string _6139 {
            get {
                return ResourceManager.GetString("6139", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代收月结卡号不能为空 的本地化字符串。
        /// </summary>
        internal static string _6140 {
            get {
                return ResourceManager.GetString("6140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效月结卡号,未配置代收货款上限 的本地化字符串。
        /// </summary>
        internal static string _6141 {
            get {
                return ResourceManager.GetString("6141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超过代收货款费用限制 的本地化字符串。
        /// </summary>
        internal static string _6142 {
            get {
                return ResourceManager.GetString("6142", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否自取件只能为 1 或 2 的本地化字符串。
        /// </summary>
        internal static string _6143 {
            get {
                return ResourceManager.GetString("6143", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否转寄件只能为 1 或 2 的本地化字符串。
        /// </summary>
        internal static string _6144 {
            get {
                return ResourceManager.GetString("6144", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否上门收款只能为 1 或 2 的本地化字符串。
        /// </summary>
        internal static string _6145 {
            get {
                return ResourceManager.GetString("6145", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回单类型错误 的本地化字符串。
        /// </summary>
        internal static string _6146 {
            get {
                return ResourceManager.GetString("6146", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清单冷冻箱费用为空或者获取冷冻箱错误 的本地化字符串。
        /// </summary>
        internal static string _6147 {
            get {
                return ResourceManager.GetString("6147", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安装费用不能为空 的本地化字符串。
        /// </summary>
        internal static string _6148 {
            get {
                return ResourceManager.GetString("6148", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安装费用转数字失败 的本地化字符串。
        /// </summary>
        internal static string _6149 {
            get {
                return ResourceManager.GetString("6149", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单不存在 的本地化字符串。
        /// </summary>
        internal static string _6150 {
            get {
                return ResourceManager.GetString("6150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报文 参数不合法 的本地化字符串。
        /// </summary>
        internal static string _8000 {
            get {
                return ResourceManager.GetString("8000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IP 未授权 的本地化字符串。
        /// </summary>
        internal static string _8001 {
            get {
                return ResourceManager.GetString("8001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务（功能）未授权 的本地化字符串。
        /// </summary>
        internal static string _8002 {
            get {
                return ResourceManager.GetString("8002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询单号超过最大限制 的本地化字符串。
        /// </summary>
        internal static string _8003 {
            get {
                return ResourceManager.GetString("8003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路由查询条数超限制 的本地化字符串。
        /// </summary>
        internal static string _8004 {
            get {
                return ResourceManager.GetString("8004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询次数超限制 的本地化字符串。
        /// </summary>
        internal static string _8005 {
            get {
                return ResourceManager.GetString("8005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已下单，无法接收订单确认请求 的本地化字符串。
        /// </summary>
        internal static string _8006 {
            get {
                return ResourceManager.GetString("8006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此订单已经确认，无法接收订单确认请求 的本地化字符串。
        /// </summary>
        internal static string _8007 {
            get {
                return ResourceManager.GetString("8007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此订单人工筛单还未确认，无法接收订单确认请求 的本地化字符串。
        /// </summary>
        internal static string _8008 {
            get {
                return ResourceManager.GetString("8008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此订单不可收派, 无法接收订单确认请求。 的本地化字符串。
        /// </summary>
        internal static string _8009 {
            get {
                return ResourceManager.GetString("8009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此订单未筛单, 无法接收订单确认请求。 的本地化字符串。
        /// </summary>
        internal static string _8010 {
            get {
                return ResourceManager.GetString("8010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不存在该接入编码与运单号绑定关系 的本地化字符串。
        /// </summary>
        internal static string _8011 {
            get {
                return ResourceManager.GetString("8011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不存在该接入编码与订单号绑定关系 的本地化字符串。
        /// </summary>
        internal static string _8012 {
            get {
                return ResourceManager.GetString("8012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未传入查询单号 的本地化字符串。
        /// </summary>
        internal static string _8013 {
            get {
                return ResourceManager.GetString("8013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 校验码错误 的本地化字符串。
        /// </summary>
        internal static string _8014 {
            get {
                return ResourceManager.GetString("8014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未传入运单号信息 的本地化字符串。
        /// </summary>
        internal static string _8015 {
            get {
                return ResourceManager.GetString("8015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重复下单 的本地化字符串。
        /// </summary>
        internal static string _8016 {
            get {
                return ResourceManager.GetString("8016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单号与运单号不匹配 的本地化字符串。
        /// </summary>
        internal static string _8017 {
            get {
                return ResourceManager.GetString("8017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未获取到订单信息 的本地化字符串。
        /// </summary>
        internal static string _8018 {
            get {
                return ResourceManager.GetString("8018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单已确认 的本地化字符串。
        /// </summary>
        internal static string _8019 {
            get {
                return ResourceManager.GetString("8019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不存在该订单跟运单绑定关系 的本地化字符串。
        /// </summary>
        internal static string _8020 {
            get {
                return ResourceManager.GetString("8020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接入编码为空 的本地化字符串。
        /// </summary>
        internal static string _8021 {
            get {
                return ResourceManager.GetString("8021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 校验码为空 的本地化字符串。
        /// </summary>
        internal static string _8022 {
            get {
                return ResourceManager.GetString("8022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务名为空 的本地化字符串。
        /// </summary>
        internal static string _8023 {
            get {
                return ResourceManager.GetString("8023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未下单 的本地化字符串。
        /// </summary>
        internal static string _8024 {
            get {
                return ResourceManager.GetString("8024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未传入服务或不提供该服务 的本地化字符串。
        /// </summary>
        internal static string _8025 {
            get {
                return ResourceManager.GetString("8025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不存在的客户 的本地化字符串。
        /// </summary>
        internal static string _8026 {
            get {
                return ResourceManager.GetString("8026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不存在的业务模板 的本地化字符串。
        /// </summary>
        internal static string _8027 {
            get {
                return ResourceManager.GetString("8027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户未配置此业务 的本地化字符串。
        /// </summary>
        internal static string _8028 {
            get {
                return ResourceManager.GetString("8028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户未配置默认模板 的本地化字符串。
        /// </summary>
        internal static string _8029 {
            get {
                return ResourceManager.GetString("8029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到这个时间的合法模板 的本地化字符串。
        /// </summary>
        internal static string _8030 {
            get {
                return ResourceManager.GetString("8030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据错误，未找到模板 的本地化字符串。
        /// </summary>
        internal static string _8031 {
            get {
                return ResourceManager.GetString("8031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据错误，未找到业务配置 的本地化字符串。
        /// </summary>
        internal static string _8032 {
            get {
                return ResourceManager.GetString("8032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据错误，未找到业务属性 的本地化字符串。
        /// </summary>
        internal static string _8033 {
            get {
                return ResourceManager.GetString("8033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重复注册人工筛单结果推送 的本地化字符串。
        /// </summary>
        internal static string _8034 {
            get {
                return ResourceManager.GetString("8034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成电子运单，必须存在运单号 的本地化字符串。
        /// </summary>
        internal static string _8035 {
            get {
                return ResourceManager.GetString("8035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册路由推送必须存在运单号 的本地化字符串。
        /// </summary>
        internal static string _8036 {
            get {
                return ResourceManager.GetString("8036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已消单 的本地化字符串。
        /// </summary>
        internal static string _8037 {
            get {
                return ResourceManager.GetString("8037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 业务类型错误 的本地化字符串。
        /// </summary>
        internal static string _8038 {
            get {
                return ResourceManager.GetString("8038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 寄方地址错误 的本地化字符串。
        /// </summary>
        internal static string _8039 {
            get {
                return ResourceManager.GetString("8039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 到方地址错误 的本地化字符串。
        /// </summary>
        internal static string _8040 {
            get {
                return ResourceManager.GetString("8040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 寄件时间格式错误 的本地化字符串。
        /// </summary>
        internal static string _8041 {
            get {
                return ResourceManager.GetString("8041", resourceCulture);
            }
        }
    }
}
